### ISSUE TITLE
Old data in API causes non-editable data to show as having been edited

### ISSUE THREAD

**Issue by jlczapski** [micronutrientsupport/micronutrient-support-tool#1069]
## Description
![image](https://user-images.githubusercontent.com/16479189/219431128-50a3120e-7c54-447c-b17f-5a14807fc6a5.png)

New updates add functionality to have non-editable inputs as greyed out, but some previously _have_ been edited where they shouldn't. This results in the behaviour in the image above.

## Possible Fix
Wipe old data from interventions in the API? Now that these fields are non-editable, it won't happen again in the future.

## Steps to Reproduce
Recurring costs > Mill inspections and monitoring > Open dialog

**Comment by Fuhji** [comment]
@bgsandan to fix this we need to wipe the user-added interventions produced during testing. Is this a good thing to clean up at end of the sprint?

**Comment by bgsandan** [comment]
Should now be resolved with fresh data load
