### ISSUE TITLE
Update "Load an intervention" dialog options

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#1144]
Currently the user can browse and access all interventions

<img width="807" alt="image" src="https://github.com/micronutrientsupport/micronutrient-support-tool/assets/39411049/f00efdc4-5b1a-4aba-9e18-ca860ca51d72">

We need to reduce the likelihood of users intentionally or maliciously editing another user's intervention.

### Long term plan

- Have a user login account system
- If logged in, a user can (optionally) save an intervention to their account
- If not logged in, or does not have an account, an intervention can be recalled by entering the intervention ID into the loading dialog
  - To reduce the risk of enumeration attack, the intervention ID will be changed to an alphanumeric UID (https://github.com/micronutrientsupport/database-architecture/issues/243) 

### Medium term plan - _Ready to implement_

- [x] Remove dropdown of all interventions
- [x] Replace with an input text box to enter an intervention ID
- [x] Clicking load, loads the intervention ID entered in the box or shows an error if no intervention returned
- [x] Add text to the UI to indicate that the user should note their ID if they want to reload the intervention (cc: @pautva for suggestions)

**Comment by bgsandan** [comment]
Additionally:

*    [ ]  If the requested intervention ID is valid (i.e. [https://api.micronutrient.support/dev/v2/interventions/\<ID>](https://api.micronutrient.support/dev/v2/interventions/<ID>) does return an intervention, but the `isTemplateIntervention` parameter is `true` then give a message indicating that that intervention is a template and cannot be directly loaded the user should go to copy & edit to created a new intervention based upon it

**Comment by DanielLyleWilliamWarren** [comment]
> Additionally:
> 
> * [ ]   If the requested intervention ID is valid (i.e. [https://api.micronutrient.support/dev/v2/interventions/<ID>](https://api.micronutrient.support/dev/v2/interventions/%3CID%3E) does return an intervention, but the `isTemplateIntervention` parameter is `true` then give a message indicating that that intervention is a template and cannot be directly loaded the user should go to copy & edit to created a new intervention based upon it

Conversation with AB this afternoon. If a request is sent to  https://api.micronutrient.support/dev/v2/interventions `/interventionID` it currently errors if the ID does not exist. AB will update endpoint with a flag to return error if `isTemplateIntervention === true`. Minor change will be needed on the front-end @bgsandan to inform when ready.

**Comment by pautva** [comment]
We could add the below text to the 'New Intervention' modal to remind users to save the intervention ID:

![reminder](https://github.com/micronutrientsupport/micronutrient-support-tool/assets/72566636/4e3bf210-1b41-44eb-8119-814c1447d957)

I've created a GitLab issues for it here:
https://github.com/micronutrientsupport/micronutrient-support-tool/issues/1165
