### ISSUE TITLE
UI prompt user to reload previously viewed interventions

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#1146]
_Depends on the UI updates in #1144 and localstorage updates in #1145_ 

Update the "Load an existing intervention" dialog to in addition to the "intervention ID" input box to support loading interventions from those stored in localstorage

Example rough UI sketch:

![](https://github.com/micronutrientsupport/micronutrient-support-tool/assets/39411049/1fe0245d-8236-47a7-8e88-7277d8b84874)

**Comment by DanielLyleWilliamWarren** [comment]
This issue will be resolved in https://github.com/micronutrientsupport/micronutrient-support-tool/pull/1166

**Comment by Sveouu** [comment]
This has been resolved
