### ISSUE TITLE
Inputs as percentages - Stage 2 'Compliance over time'

### ISSUE THREAD

**Issue by DanielLyleWilliamWarren** [micronutrientsupport/micronutrient-support-tool#1150]
- [ ] All inputs in table to be percentages & round to 2 decimal places

![image](https://github.com/micronutrientsupport/micronutrient-support-tool/assets/38860838/f4015ba6-4211-4442-86ed-e553ef731a2a)

**Comment by Fuhji** [comment]
closed in #1169
