### ISSUE TITLE
Recurring cost year title

### ISSUE THREAD

**Issue by kpitten** [micronutrientsupport/micronutrient-support-tool#1249]
In the recurring costs sections, the year labels currently say "year of start-up or scale-up". Should just be "Intervention year"
![Screenshot 2023-10-06 182605](https://github.com/micronutrientsupport/micronutrient-support-tool/assets/37812052/c88db74a-d5e3-4206-9543-d060b64c3b86)

**Comment by bgsandan** [comment]
Fixed awaiting redployment
