### ISSUE TITLE
Calculated values not workin

### ISSUE THREAD

**Issue by kpitten** [micronutrientsupport/micronutrient-support-tool#1266]
(title should be working not workin :))
When I change the assumptions (on both the baseline assumptions and performance over time pages) about the percent of the food vehicle that is fortified to any extent and the fortifiable food vehicle in the food system, the calculated values below should correspondingly change but don't.
![Screenshot 2023-10-16 135108](https://github.com/micronutrientsupport/micronutrient-support-tool/assets/37812052/b2f31b85-7444-45ef-aa9d-a0eeae578cc0)

**Comment by bgsandan** [comment]
Should now be working in version 1.14.0
