### ISSUE TITLE
Calculation of fortification level

### ISSUE THREAD

**Issue by kpitten** [micronutrientsupport/micronutrient-support-tool#1281]
I just noticed that when you change the "Fortifiable wheat flour that is fortified to any extent*" field calculated values below change correspondingly, but when you change "Average fortification level among fortified wheat flour as a percent of the standard*" nothing changes. Both parameters should change the calculated values (as in the spreadsheets). 
![Screenshot 2023-11-01 170726](https://github.com/micronutrientsupport/micronutrient-support-tool/assets/37812052/2616140b-f2f7-45f9-af4e-1a4fb46bcf59)

**Comment by bgsandan** [comment]
Should now be working in version 1.14.0
