### ISSUE TITLE
Cost-effectiveness module landing page help button (question mark)

### ISSUE THREAD

**Issue by kpitten** [micronutrientsupport/micronutrient-support-tool#1334]
The current text included in the help button/questions mark is pasted below. Let's replace it with the following. Thanks!

The Cost-Effectiveness Module

The cost-effectiveness module of the MAPS tools provides a modeling framework to predict and compare the cost, effectiveness, cost-efficiency (i.e., cost per unit of output), and cost-effectiveness (i.e., cost per unit of impact) of micronutrient intervention programs. You can use just the costing functionality, just the effectiveness functionality, or both. 

The **costing functionality** provides a modeling framework to estimate micronutrient intervention costs over a 10-year time horizon using an activity- and ingredients-based costing approach. The **effectiveness functionality** provides a modeling framework for using household consumption and expenditure survey data or food balance sheet data to predict the change in the micronutrient adequacy of diets as a result of a micronutrient intervention. **Together**, these estimates can be used to predict and compare the cost-efficiency (cost per capita, cost per household reached, etc.) and cost-effectiveness (cost per household with adequate apparent micronutrient intake as the result of an intervention) of micronutrient intervention programs. 

![Screenshot 2024-02-22 130303](https://github.com/micronutrientsupport/micronutrient-support-tool/assets/37812052/e74d195c-b110-4afd-a1e4-ac406f680b95)

**Comment by bgsandan** [comment]
Udpated in version 1.14.0
