### ISSUE TITLE
Create new intervention screen

### ISSUE THREAD

**Issue by kpitten** [micronutrientsupport/micronutrient-support-tool#1335]
On the current create a new intervention screen (screenshot below), let's revise the text to the following (for consistency in labeling, let's also revise the text on the button to 'create intervention'):

Create a Micronutrient Intervention

To model the cost and/or effectiveness of a micronutrient intervention, begin by clicking the button below to create the intervention. After you’ve created and stored one intervention, you will be able create additional interventions and compare results across interventions. 
![Screenshot 2024-02-22 143822](https://github.com/micronutrientsupport/micronutrient-support-tool/assets/37812052/a0706aec-35ca-427e-bf62-2679d8f5acaa)

**Comment by bgsandan** [comment]
Udpated in version 1.14.0
