### ISSUE TITLE
Selected interventions screen

### ISSUE THREAD

**Issue by kpitten** [micronutrientsupport/micronutrient-support-tool#1336]
Let's change the "Selected Interventions" header to "Created Interventions". Also, let's drop the "Base year: 2023". Finally, let's change the purple button label from "Review" to "Edit" to communicate the need for actually making changes in the models. 

![Screenshot 2024-02-22 145006](https://github.com/micronutrientsupport/micronutrient-support-tool/assets/37812052/48d6f47a-1b3c-443e-a551-5f14c392041f)

**Comment by bgsandan** [comment]
Udpated in version 1.14.0
