### ISSUE TITLE
Sidebar text

### ISSUE THREAD

**Issue by kpitten** [micronutrientsupport/micronutrient-support-tool#1337]
Let's change the text of step 3 in the sidebar instructions to read:

"Edit the intervention"

![Screenshot 2024-02-22 145524](https://github.com/micronutrientsupport/micronutrient-support-tool/assets/37812052/d5534bad-06c1-48ce-a37e-9b8c421e5507)

**Comment by bgsandan** [comment]
Udpated in version 1.14.0
