### ISSUE TITLE
Update browser tab title to reflect location in app

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#150]
At the least, section e.g. "Micronutrient Action Policy Support: Quick MAPS". 

Could also reflect current data/selection

**Comment by pautva** [comment]
Some suggestions for titles, descriptions and keywords for pages. Feel free to edit and expand the list.

| Page                    | Title                                                                 | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | Keywords                                                                  |
|-------------------------|-----------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------|
| Home                    | Micronutrient Action Policy Support (MAPS): Homepage                  | MAPS is a web-hosted tool, communicating estimates of dietary micronutrient (MN) supplies and deficiency risks at national and sub-national scales in Africa. The tool draws on MN biomarker survey data where these are available, and dietary MN supply estimates derived from nationa-scale (Food Balance Sheets) or sub-national (House-hold Consumption and Expenditure Survey) data, presenting the user with multiple perspectives on MN deficiency risks and highlighting where there ar emajro data gaps. | Micronutrients; maps; policy                                              |
| Maps Tool Interface     | Micronutrient Action Policy Support: Tools                            | Various tools to explore micronutrient deficiencies in your geography of interest and possible interventions to mitigate the micro-nutrient deficiencies.                                                                                                                                                                                                                                                                                                                                                          | Micronutrients; maps; tools; interventions                                |
| Quick maps: Baseline    | Micronutrient Action Policy Support: Quick Maps - Baseline            | Baseline estimates of dietary MN supplies and deficiency risks in the selected country or region.                                                                                                                                                                                                                                                                                                                                                                                                                  | Maps; micronutrients; national; sub-national; Africa; dietary; deficiency |
| Quick maps: Projections | Micronutrient Action Policy Support: Quick Maps - Projections to 2050 | Projections of food system changes under various scenarios.                                                                                                                                                                                                                                                                                                                                                                                                                                                        | projections; scenarios; micronutrients; food systems;                     |
