### ISSUE TITLE
What will/should the 'new window' icon on a card do?

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#175]

**Comment by DanielLyleWilliamWarren** [comment]
@bgsandan  @jon571 , any objections to this issue being closed?

**Comment by jon571** [comment]
Nope.  I think we've decided that it opens a modal with a larger version of what went in the card, with potentially more options/interactions available.

**Comment by DanielLyleWilliamWarren** [comment]
Closing the issue on the understanding that "it opens a modal with a larger version of what went in the card, with potentially more options/interactions available."
