### ISSUE TITLE
As a Quick MAPS User, I want to share the current dashboard via a URL, So I can get bookmark it for later or share with colleagues

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#18]
# User story
As a Quick MAPS User, I want to share the current dashboard via a URL, So I can get bookmark it for later or share with colleagues

# Acceptance criteria

- [ ] Current state of the tool (selected nation, micronutrient etc.) is stored in the URL params.
- [ ] Loading a page with URL params loads the appropriate data/visualisations
- [ ] UI provides a means to view/copy the permalink to the current state

**Comment by Sveouu** [comment]
visualization JS libraries:


![image](https://user-images.githubusercontent.com/72437441/99248584-9a5f9b00-2800-11eb-9967-f6deb278d29c.png)
