### ISSUE TITLE
Projections page description

### ISSUE THREAD

**Issue by pautva** [micronutrientsupport/micronutrient-support-tool#213]
# User story
As a policy-maker, I want to understand how the projections are modelled, so I can can make informed decisions

# Summary

Provide a quick overview and a more detailed overview of different scenarios used in 'Projections to 2050' page.

## Component

![image](https://user-images.githubusercontent.com/72566636/105739649-3b20b400-5f30-11eb-8e73-fb47ec878dec.png)

## Location

![image](https://user-images.githubusercontent.com/72566636/105740591-3c061580-5f31-11eb-9d14-3ea138185966.png)

# Details

- [x] User can see the nation and micronutrient selected in the 'quick overview' card
- [x] There is a brief description of scenarios used
- [x] If users click 'Learn more', they can see a more details description of scenarios:

![image](https://user-images.githubusercontent.com/72566636/105389521-d7387b80-5c0f-11eb-9d08-0618bcc5fd3c.png)

- [x] Users can click the cross or anywhere outside the modal to come back to the projections page.
- [x] The card is responsive
- [x] (Nice to have) User can minimize the overview to hide scenario descriptions
![image](https://user-images.githubusercontent.com/72566636/105740681-54763000-5f31-11eb-863d-c80da8ec4a8b.png)

# Resources

[API for scenario descriptions](https://api.micronutrient.support/projection-scenario)

<details>
<summary>Short scenarios description</summary>
<br>
The projections are modelled based on 3 different scenarios. Scenario SSP1 is called the Sustainability scenario; scenario SSP2 is the Middle of the Road scenario; scenario SSP3 is the Regional Rivalry Scenario.
</details>

<details>
<summary>Detailed scenarios description</summary>
<br>
SSP1 - Sustainable development is realized, with relatively high levels of investment in research and development, which leads to rapid technological change (with a sustainable focus), decreasing inequality, lower energy intensity, and high land productivity. This development pathway leads to a future where society is able to relatively easily mitigate or adapt to climate change. There are a high rate of economic growth, declining population growth, and increasing levels of education globally. 
SSP2 - This is a middle-of-the-road scenario that follows historical trends. Economic development continues but is not uniform. Environmental degradation continues but at a slowing pace. There is general improvement, but it is much slower than that seen in SSP 1. Climate change presents moderate challenges to both adaptation and mitigation. 
SSP3 - This is a fairly negative future pathway characterized by increasing nationalism with greater levels of conflict and challenges to global and regional cooperation. Barriers to trade increase, and countries tend to look inward at the expense of global cooperation. There are lower levels of technological change. Economic development is slow, and population growth is higher. Climate change presents significant challenges for both adaptation and mitigation.
</details>

[Link to prototype](https://www.figma.com/proto/swhv1D7WScZwDE5KKYkkaE/BMGF-Maps?node-id=833%3A13268&viewport=398%2C454%2C0.046554576605558395&scaling=contain)

# Acceptance criteria

- [ ] People using the maps app for the first time can easily learn about different types of scenarios used in the projections

# Sprint Ready Checklist 
1. - [ ] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable 
5. - [ ] External / 3rd Party dependencies identified

**Comment by bgsandan** [comment]
@Fuhji - The descriptions of the scenarios for the more detail modal will shortly be available at https://api.micronutrient.support/projection-scenario (once deployment finishes)

The short descriptions for the brief summary card aren't yet in the db but will be added to the DB/API endpoint asap

**Comment by bgsandan** [comment]
API response updated to include the brief description text and which scenario is the 'baseline' scenario'

Endpoint: https://api.micronutrient.support/projection-scenario
OpenAPI doc: https://api.micronutrient.support/explorer
