### ISSUE TITLE
Quick summary card

### ISSUE THREAD

**Issue by pautva** [micronutrientsupport/micronutrient-support-tool#216]
# User story
As a policy-maker, I want to get a quick overview of the projections for my selected nutrient, so I can decide whether I want to explore those projections in more details

# Summary

Provide a quick summary of projections

## Recent changes (1-27-21)

- [ ] Clarify the Estimate heading - Estimate (2010). The reason Sherwin suggests 2010 is that all the scenarios will have that same historic base then, and we can base it back to underlying data from FAO. 
![image](https://user-images.githubusercontent.com/72566636/106032202-15c6ae00-60c8-11eb-966f-81e210f567b5.png)

- [ ] Remove the option to switch between person, household and nation. It will always be just Person
![image](https://user-images.githubusercontent.com/72566636/106032136-00518400-60c8-11eb-92bc-77f4d7728cb4.png)

- [ ] Default selection should be _mg per person per day_. It is the most used indicator.

- [ ] Added [mobile layout mockup](https://user-images.githubusercontent.com/72566636/106032810-da78af00-60c8-11eb-8982-9596cb8c829c.png)

## Component

![image](https://user-images.githubusercontent.com/72566636/106033288-83bfa500-60c9-11eb-9b06-596e6b6ab34d.png)

## Location

Explore projections tab

![image](https://user-images.githubusercontent.com/72566636/106033461-b2d61680-60c9-11eb-89cd-d114b9c3cdb4.png)

# Details

- [ ] Show the current estimate which is based on the SSP2 (middle of the road) scenario (it changes based on measuring unit selected)
- [ ] Show the target - recommended nutrient intake (NRI) for this nutrient (it changes based on measuring unit selected)
- [ ] Show the difference between estimate and target  (it changes based on measuring unit and time period selected)
- [ ] You can change measuring units and it updates the figures displayed
- [ ] You can change the time period and it displays the figures displayed
- [ ] Show the year when the 'business as usual' will reach the target
- [ ] Hovering question near target date, you get more details about this figure
![image](https://user-images.githubusercontent.com/72566636/105471262-756d2580-5c92-11eb-9f24-87475f38d184.png)
- [ ] The card is responsive
![image](https://user-images.githubusercontent.com/72566636/105741671-8045e580-5f32-11eb-89bb-3dbc4dd4dcf4.png)

# Resources

<details>
<summary>Target number explanation text</summary>
<br>
Using moderate assumptions of economic and population growth, and no interventions (scenario SSP2), per capita consumption of [micronutrient name] micronutrient is expected to reach recommended levels by 2021.
</details>

# Acceptance criteria

- [ ] People using the maps app for the first time can get a quick overview of the projections and decide whether they want to explore them in more detail

# Sprint Ready Checklist 
1. - [x] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable 
5. - [ ] External / 3rd Party dependencies identified

**Comment by Fuhji** [comment]
Is there API/data for this available?
