### ISSUE TITLE
MN availability card

### ISSUE THREAD

**Issue by pautva** [micronutrientsupport/micronutrient-support-tool#217]
# User story
As a nutritionist, I want to understand how MN availability will change in the near future, so I can make informed recommendations. I also want to export the data and charts for use in my reports.

# Summary

Provide MN availability data in chart and table form

[Figma prototype](https://www.figma.com/proto/swhv1D7WScZwDE5KKYkkaE/BMGF-Maps?node-id=833%3A13268&viewport=-57736%2C-16063%2C1.8460657596588135&scaling=contain)

## Component

Chart
![image](https://user-images.githubusercontent.com/72566636/106149736-82968280-6172-11eb-9c34-053d7cd76233.png)

Table 
![image](https://user-images.githubusercontent.com/72566636/106149815-9641e900-6172-11eb-8768-5ad46f2bed6f.png)

Download
![image](https://user-images.githubusercontent.com/72566636/106149880-a78af580-6172-11eb-8b55-aeaf06535f9a.png)

## Location

Quick maps > Projections

![image](https://user-images.githubusercontent.com/72566636/106150362-2ed86900-6173-11eb-9136-b778045823a2.png)

# Details

- [x] A line chart shows how the MN availability will change
- [x] Line chart has a heading, description and source
- [ ] Table shows the data for three different scenarios (TO CONFIRM - table columns: year, SSP1, % change from index, SSP2, % change from index, SSP3, % change from index) [Is index = 2010 data?]
- [x] Table has a heading and description
- [x] Expand the card
- [x] Move and resize the card
- [x] Clicking on the question mark near the scenarios provides the description of the scenarios
![image](https://user-images.githubusercontent.com/72566636/105479328-3c39b300-5c9c-11eb-9138-8ac0894dc4e4.png)

- [ ] (NICE TO HAVE) You can download line chart as *.png file
- [ ] (NICE TO HAVE)You can download line chart as *.svg
- [ ] (NICE TO HAVE) You can download the data in the table in a *.csv format

# Resources

<details>
<summary>API data</summary>
<br>
The data for the table can be accessed via 

`https://api.micronutrient.support/projection-total`

Filtering by country can be acheived via filtering, e.g. for Malawi:
`https://api.micronutrient.support/projection-total?filter={"where":{"country":"MWI"}}`

Limiting to a given micronutrient can be acheived via e.g. for Calcium:
`https://api.micronutrient.support/projection-total?filter={"where":{"country":"MWI"},"fields":{"scenario":true,"year":true,"Ca":true,"CaDiff":true}}`

There *may* in the future be a utility endpoint to ease filtering by Country/Mn e.g. `/projection-total/<COUNTRY>/<MN>` but the above should suffice for now
</details>
<details>
<summary>Text description for chart</summary>
<br>
The data shows the projected total MN availability per person per day (mg per person per day). 
</details>
<details>
<summary>Text description for table</summary>
<br>
The data shows the projected total MN availability per person per day for each year (g per person). The percentage shows the average annual change between five year periods,
</details>
<details>
<summary>Text for scenario description</summary>
<br>
SSP1 - Sustainable development is realized, with relatively high levels of investment in research and development, which leads to rapid technological change (with a sustainable focus), decreasing inequality, lower energy intensity, and high land productivity. This development pathway leads to a future where society is able to relatively easily mitigate or adapt to climate change. There are a high rate of economic growth, declining population growth, and increasing levels of education globally. 
SSP2 - This is a middle-of-the-road scenario that follows historical trends. Economic development continues but is not uniform. Environmental degradation continues but at a slowing pace. There is general improvement, but it is much slower than that seen in SSP 1. Climate change presents moderate challenges to both adaptation and mitigation. 
SSP3 - This is a fairly negative future pathway characterized by increasing nationalism with greater levels of conflict and challenges to global and regional cooperation. Barriers to trade increase, and countries tend to look inward at the expense of global cooperation. There are lower levels of technological change. Economic development is slow, and population growth is higher. Climate change presents significant challenges for both adaptation and mitigation.
</details>

# Acceptance criteria

- [ ] Nutritionists can easily see how MN availability is expected to change in the future and they can download the data and charts for their own reports.

# Sprint Ready Checklist 
1. - [ ] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable 
5. - [ ] External / 3rd Party dependencies identified

**Comment by bgsandan** [comment]
The data for the table is now available via the API.  Details added to the issue
