### ISSUE TITLE
Food sources card

### ISSUE THREAD

**Issue by pautva** [micronutrientsupport/micronutrient-support-tool#218]
# User story
As a nutritionist, I want to know what are the projected food sources for selected micronutrient, so I can adjust my recommendations and guidelines

# Summary

Provide an overview of food sources for selected nutrient grouped by commodity or food group under 3 different scenarios.

## Component

Chart
![image](https://user-images.githubusercontent.com/72566636/106155667-d7d59280-6178-11eb-9eb6-f69bb8127e8e.png)

Table
![image](https://user-images.githubusercontent.com/72566636/106155983-f2a80700-6178-11eb-8022-7f94f6355d4f.png)

Download
![image](https://user-images.githubusercontent.com/72566636/106156079-05bad700-6179-11eb-9f85-97754129c1c0.png)

## Location

Quick Maps > Projections to 2050 tab

![image](https://user-images.githubusercontent.com/72566636/106155797-e4f28180-6178-11eb-9e2a-45921d7e9a26.png)

# Details

- [ ] View the data in a bar chart
- [ ] Chart has title, description and source details
- [ ] Change what data is being displayed in the chart 
![image](https://user-images.githubusercontent.com/72566636/106156643-b2955400-6179-11eb-868f-7279983a3959.png)
- [ ] View the data in a table form 
- [ ] Change what data is being displayed in the table
![image](https://user-images.githubusercontent.com/72566636/106156621-ac9f7300-6179-11eb-9d02-4ab97ef7db9e.png)
- [ ] Clicking on the question provides more details about different types of scenarios
- [ ] Move and resize the card
- [ ] Expand card
- [ ] (NICE TO HAVE) download data as PNG, SVG or CSV

# Resources

<details>
<summary>Text description for chart</summary>
<br>
The graph shows main food sources for [mn] in [nation].
</details>
<details>
<summary>Text description for table</summary>
<br>
Top 5 items contributing to Calcium consumption - grams per person per day.
</details>
<details>
<summary>Text for scenario description</summary>
<br>
SSP1 - Sustainable development is realized, with relatively high levels of investment in research and development, which leads to rapid technological change (with a sustainable focus), decreasing inequality, lower energy intensity, and high land productivity. This development pathway leads to a future where society is able to relatively easily mitigate or adapt to climate change. There are a high rate of economic growth, declining population growth, and increasing levels of education globally. 
SSP2 - This is a middle-of-the-road scenario that follows historical trends. Economic development continues but is not uniform. Environmental degradation continues but at a slowing pace. There is general improvement, but it is much slower than that seen in SSP 1. Climate change presents moderate challenges to both adaptation and mitigation. 
SSP3 - This is a fairly negative future pathway characterized by increasing nationalism with greater levels of conflict and challenges to global and regional cooperation. Barriers to trade increase, and countries tend to look inward at the expense of global cooperation. There are lower levels of technological change. Economic development is slow, and population growth is higher. Climate change presents significant challenges for both adaptation and mitigation.
</details>

# Acceptance criteria

- [ ] Nutritionists can explore the food sources for selected MN and to export the data for use in their papers and reports

# Sprint Ready Checklist 
1. - [ ] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable 
5. - [ ] External / 3rd Party dependencies identified

**Comment by Fuhji** [comment]
Is there data and/or API availability for this to be started? @bgsandan

**Comment by bgsandan** [comment]
Sorry, have been having internet issues. Pulling sample data out of DB now
