### ISSUE TITLE
Can't use scroll bars on re-sizeable grid squares as re-size overrides scroll.

### ISSUE THREAD

**Issue by DanielLyleWilliamWarren** [micronutrientsupport/micronutrient-support-tool#264]
Re-size functionality is preventing user from scrolling with mouse click (scroll wheel still works). 

- Bug can be replicated by: Quickmaps > Explore projections to 2050 > Projection Availability
- Attempt scroll using scroll bar located on chart or table.

**Comment by jon571** [comment]
I did put a styling change in to the baseline page to solve this.

I'll move it to affect all gridsters.
