### ISSUE TITLE
Visual bug in country select

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#295]
# Summary

In Firefox (Windows and Mac) the "Geography of Interest" labels overflow the fieldset outline

<img width="354" alt="Screenshot 2021-02-26 at 16 23 01" src="https://user-images.githubusercontent.com/39411049/109326564-43ca1a00-784f-11eb-8ec9-1d2bc887a0a0.png">

# Acceptance criteria

- [ ] Fix CSS so that text displayed correctly as per the other sections

**Comment by jon571** [comment]
I just had a play and googled this a bit.  This might be the answer:
https://stackoverflow.com/questions/63304170/flexbox-not-working-properly-for-legend-on-firefox

So, have a single span in the legend element and style that instead of the legend element.  Should apply that to all the legends too.
