### ISSUE TITLE
Separate summary card contents for different pages/modes

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#325]
# Summary

All dashboard pages should contain a summary card highlighting the selections/type of data that is being displayed on that page, along with a collapsible panel with extended text content explaining the current page.

# Acceptance criteria

- [ ] Diet Baseline, Diet Projections and Biomarker pages all contain summary card
- [ ] Diet Baseline and Diet Projection summary cards header contain summary of the data being displayed on that page as per screenshots in #301 (data comes from sidebar selections/API responses
- [ ] Biomarker summary card header contains fields from #301 screenshot except 'Baseline assumption'.  Additional fields TBC
- [ ] Projections summary card contains the current text explaining scenarios
- [ ] Baseline summary card text is Lorem Ipsum dummy text
- [ ] Biomarker summary card text is Lorem Ipsum dummy text

**Comment by bgsandan** [comment]
@Fuhji hopefully this clarifies, but if still unclear or other queries, just shout

**Comment by Fuhji** [comment]
waiting on #298 and #299 before can progress
