### ISSUE TITLE
Only display IMPACT model pages/components if the data allows

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#328]
# Summary

Not all Micronutrients in the tool have corresponding data in the IMPACT model.  When selecting a micronutrient from the `/micronutrient` API endpoint the `is_in_impact` flag indicates whether there is data.  The IMPACT components/pages should only be displayed if this is true

# Acceptance criteria

- [x] If `is_in_impact` is false for the chosen micronutrient, the projections summary panel should not be displayed
- [x] If `is_in_impact` is true for the chosen micronutrient, the projections summary panel should be displayed:
![image](https://user-images.githubusercontent.com/39411049/109799602-1ea12700-7c14-11eb-9490-6b36efdc13ba.png)
- [x] If `is_in_impact` is false for the chosen micronutrient, the "Explore projections to 2050" button should be disabled:
<img width="1380" alt="Screenshot 2021-03-03 at 11 34 08" src="https://user-images.githubusercontent.com/39411049/109799903-79d31980-7c14-11eb-8cbf-600fe760f4cb.png">

**Comment by jon571** [comment]
So if we're on the projections page when the micronutrient is changed to a is_in_impact = false value, do we navigate to the baseline page @bgsandan ?

**Comment by bgsandan** [comment]
Yep, that makes sense
