### ISSUE TITLE
Add a notification mechanism

### ISSUE THREAD

**Issue by jon571** [micronutrientsupport/micronutrient-support-tool#331]
# User story
As a user I want to see when the app makes an API call that fails.

In apps like this we normally have an notification service that triggers the display of a notification and I think we have used this before:
https://material.angular.io/components/snack-bar/overview

SHould be integrated here:
https://github.com/micronutrientsupport/micronutrient-support-tool/blob/develop/src/app/apiAndObjects/api/mapsHttpResponseHandler.ts#L68

Like this:
https://kwvmxgit.ad.nerc.ac.uk/bgs-lims/bgs-lims-gui/-/blob/develop/src/app/apiAndObjects/api/myHttpCallErrorHandler.ts#L33

*Ideally, this is in the issue title, but if not, you can put it here. If so, delete this section.*

# Acceptance criteria

- [ ] This is something that can be verified to show that this user story is satisfied.

# Sprint Ready Checklist 
1. - [ ] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable 
5. - [ ] External / 3rd Party dependencies identified

**Comment by jon571** [comment]
Hi @pautva 
I'm not sure if you have some time to design the look of a notification?

**Comment by pautva** [comment]
Hi @jon571. Yes, I can design a notification in Figma. I'll upload it here shortly for feedback.

**Comment by pautva** [comment]
@jon571 , I've added an error page to Figma prototype. Is that the type of notification you were after?

![error](https://user-images.githubusercontent.com/72566636/109839431-009cec00-7c3f-11eb-93ee-7d145bbe3cf5.png)

It can be found here:
https://www.figma.com/proto/swhv1D7WScZwDE5KKYkkaE/BMGF-Maps?node-id=1672%3A0&viewport=-57736%2C-16063%2C1.8460657596588135&scaling=contain

**Comment by jon571** [comment]
Hi @pautva.

There definitely needs to be the notification for individual api call errors.

I think there needs to be some sort of prominent standard error display that a "we can't do this at this time, try/do this" like the page you showed. The use case I had in mind was going to quickmaps baseline with invalid parameters set (after sharing a url).  At the moment it would just relocate to he quickmaps location search, but it should be clear that they haven't been able to navigate to the desired location.  This could be a dedicated page, or it might be more re-usable in a modal (we could use it as both).

I think a better card error display could be good too.  At the moment we show "error...".  In the case where a card depends on data from an API endpoint that fails in isolation, I think just showing the error in the card and letting the user continue with the rest of the site is preferable to displaying the page/modal "we can't do this at this time, try/do this".

All of these should probably have customizable message sections.

**Comment by jon571** [comment]
Inviting @bgsandan to the party 🥳

**Comment by pautva** [comment]
I see, so it would more like a 404 page for misspelt URLs. 

![image](https://user-images.githubusercontent.com/72566636/109942115-c7f72400-7ccb-11eb-97d1-a747db79e139.png)

And the error for individual cards could look something like this:

![card-not-loading-data](https://user-images.githubusercontent.com/72566636/109942220-e52bf280-7ccb-11eb-9a51-8f4e23251dbc.png)

**Comment by jon571** [comment]
Sort of, but maybe less than a 404.  Maybe just saying something about invalid parameters/selections and that you have been/are being redirected to the page where you can make valid selections.

@bgsandan do you have any suggestions for when a previously shared link to the baseline page, say, isn't valid (due to data changes/mis-copied link/attempt to change param in url)?

**Comment by bgsandan** [comment]
Hmm, that is a really interesting one.  I guess there are a few options:

a) force a 'redirect' back to the start page of quick MAPS and make them select everything again (with or without a modal/snack-bar to tell them what has happened)
b) redirect back but try to pre-fill what is valid from the URL params
c) go to some other error state with explanation of what went wrong.  Give options to then reselect the bits that are invalid/missing though is going to get messy/unwieldy very quickly
d) go to some other error state with a link to click to go back to a) or b)
e) something else I haven't thought of.

As an aside, I like @pautva in card error message for localised data fails but agree something for wider param issues also needed

**Comment by jon571** [comment]
At present the route guard stops the navigation to the page and redirects back to the quickmaps root, pre-populating what options it can.
I like this but I think there should be some confirmation to the user that this is what has happened, otherwise they my think the link worked but they're not seeing what the sharer told them they would see.  This confirmation could just be a small modal with a message "Invalid parameters were detected in your url.  Please make alternative selection."

**Comment by jon571** [comment]
Strikes me that this issue might spawn a few new task issues :-)

**Comment by pautva** [comment]
The error before redirecting people back to Quick Maps could look something like this:

![data-not-loaded](https://user-images.githubusercontent.com/72566636/109969993-76ab5c80-7cec-11eb-8c4f-3dc3d2f0ca2d.png)

**Comment by jon571** [comment]
So do we think that this should spawn 3 separate issues?
- Notification toast
- 404 page
- A modal that can be shown that for invalid parameters

**Comment by pautva** [comment]
I've created an issue for the notification toast. Feel free to add more details. I'll create the other two now.

https://github.com/micronutrientsupport/micronutrient-support-tool/issues/338

**Comment by jon571** [comment]
Are we keeping this issue open too?
If not then #338 could maybe do with being updated to reflect the more general functionality needed from the notifications, as if they are implemented with just this single use case in mind, the functionality might not include this one:

As a user I want to see when the app makes an API call that fails.
be integrated here:
https://github.com/micronutrientsupport/micronutrient-support-tool/blob/develop/src/app/apiAndObjects/api/mapsHttpResponseHandler.ts#L68

Like this:
https://kwvmxgit.ad.nerc.ac.uk/bgs-lims/bgs-lims-gui/-/blob/develop/src/app/apiAndObjects/api/myHttpCallErrorHandler.ts#L33

**Comment by pautva** [comment]
That's a good point. I can add more details to #338 and close this one.
