### ISSUE TITLE
Update Top 20 Foods card to use live API data

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#342]
# Summary

`/diet/`{datalevel[country/household]}`/top20/`{countryId}`/`{micronutrientId}`/`{compositionId}`/`{consumptionId}

<img width="1419" alt="Screenshot 2021-03-08 at 07 21 34" src="https://user-images.githubusercontent.com/39411049/110288056-5840ac00-7fdf-11eb-9766-1474c034cd7c.png">

## Differences from demo static json data

`Value` -> `mnConsumedPerDay`
`FoodexName` -> `foodName`

Depends on #341

**Comment by jon571** [comment]
I've pushed changes to the dw_342 branch to make this endpoint live.

I tried three selections:
- one had a null in the "consumptionId" response and resulted in an error - correct :-)
- two made successful calls that resulted in an empty array response

**Comment by jon571** [comment]
#367 should complete this task

**Comment by jon571** [comment]
@bgsandan I added the for review label here, although this is a purely dev issue, so there's not much to review.
