### ISSUE TITLE
Integrate share button into quick MAPS pages

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#374]
# User story
As a user I want to be able to share the current quick MAPS page I am viewing (including URL query params)

@pautva may have input as to the best place to put this.  In the mini footer perhaps?

# Acceptance criteria

- [x] Share interface from the homepage is also integrated on quick MAPS pages
- [x] Quick MAPS share button shares the current url complete with URL params for query string

**Comment by pautva** [comment]
I think having it at the top of the page would make it easier to find and more likely to use.

I see that we don't have an H1 heading on the dashboard at the moment. It might be useful to include it for accessibility reasons and so people can make sense of where they are quicker. Then the Share button could be next to the heading.

It could look like this:

Diet Data:
![share-button](https://user-images.githubusercontent.com/72566636/110795255-8982db80-826e-11eb-8ce1-7c1e7de20190.png)

Biomarker Data:
![Biomarker Results](https://user-images.githubusercontent.com/72566636/110795269-8e478f80-826e-11eb-8486-44012feefe7c.png)

**Comment by Fuhji** [comment]
Is the Blue-Purple gradient placeholder or Final Form @pautva ?

**Comment by pautva** [comment]
I'd say it's final unless anyone has any objections. I think it makes it stand out slightly, but not too much. It uses one of the purple colours that we already have in UI (#9B51E0) and a new light blue: #00DBDE

CSS properties from Figma:

background: linear-gradient(82.03deg, #00DBDE -1.03%, #9B51E0 100%);
box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
border-radius: 2px;

**Comment by Fuhji** [comment]
Please can you clarify on h1 title requirements as the figma mockup doesn't match the screenshots above @pautva ? Does the Country name need adding to each page title format?

- Baseline: Title?
- Explore Projections to 2050: Title?
- Explore simple dietary change scenarios: Title?
- Explore cost effectiveness scenarios: Title?

**Comment by pautva** [comment]
To keep it consistent with the Biomarker Data page, we should probably just follow the same heading structure for diet data pages: [Nation] Diet Data. 

And I think we can keep the same heading for all the Diet Data tabs.  The tabs themselves serve as a smaller subheading.

**Diet data:**
![image](https://user-images.githubusercontent.com/72566636/116221950-03e7bc00-a746-11eb-9114-1aacf4da902b.png)

**Biomaker data**
![image](https://user-images.githubusercontent.com/72566636/116221973-09dd9d00-a746-11eb-997e-f763d6870e01.png)

The prototype should be updated now.

**Comment by Fuhji** [comment]
@pautva @bgsandan this has been merged into `develop` as of PR #456 . Please can you close this issue if you are happy it is completed.

**Comment by pautva** [comment]
Looks good. Tested it on Diet Data and Biomarker Data pages. Closing the issue.
