### ISSUE TITLE
Setup download functionality (png) for chart.js charts using quickchart service

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#404]

**Comment by Fuhji** [comment]
This is available for all charts now except the Tree Chart, as this uses a custom chart plugin.

**Comment by Fuhji** [comment]
@bgsandan Please can you review and either close if completed or comment if more required?

**Comment by bgsandan** [comment]
This looks great 👍 .  Closing this issue.  Any future bugs or tweaks can have their own issues
