### ISSUE TITLE
Downloadable charts

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#405]
# User story

As a user I want to be able to download displayed charts as images (for inclusion in reports, presentations etc).

# Child Issues

## Front-End

- https://github.com/micronutrientsupport/micronutrient-support-tool/issues/404

## API

- https://github.com/micronutrientsupport/api/issues/95
- https://github.com/micronutrientsupport/api/issues/96

## Database

- N/A

# Acceptance Criteria

- [x] Components with a chart contain a download tab where the chart can be downloaded as a png file
- [x] Downloaded charts are watermarked with MAPS logo/URL details

**Comment by Fuhji** [comment]
All available except Tree Chart currently

**Comment by Fuhji** [comment]
@bgsandan Pleas can you review and decide if this can be closed?

**Comment by bgsandan** [comment]
Yep, good work! :smile:
