### ISSUE TITLE
Add summary card to biomarker page

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#417]
# **User story**

As a policy-maker, I want to see a short description of the data I'm looking at in one place so I don't mix it data I have open on another tab. 

## Summary

A host summary for the data selected on biomaker data page. Data should be fed from the selections made in the quick MAPS sidebar which are passed to the biomarker page in the query params (similar to the diet pages)

<img width="685" alt="Screenshot 2021-04-16 at 15 11 41" src="https://user-images.githubusercontent.com/39411049/115037432-5d3e2880-9ec6-11eb-91be-2ed986e7e586.png">

[Figma prototype](https://www.figma.com/proto/swhv1D7WScZwDE5KKYkkaE/BMGF-Maps?node-id=1767%3A2426&viewport=-4666%2C-4960%2C0.269345760345459&scaling=contain&page-id=0%3A1&hide-ui=1)

## Location

![szoter_annotated_image (2)](https://user-images.githubusercontent.com/72566636/115145769-2b0a0380-a04b-11eb-8c87-44b6ecc8c353.jpeg)

## Resources

[TO DO] - a summary of how and when the data was collected

# **Related Issues**

#416 
#419 Data source drop down in the sidebar for biomarker data

# **Acceptance Criteria**

*   [ ] Summary card is displayed at the top of the biomarker data page
*   [ ] The card shows nation, vitamin, data level, a measure of MN, age-gender group, data source, year and short summary of how data was collected.
*  [ ] The card can be minimized to hide the text description
![image](https://user-images.githubusercontent.com/72566636/115145693-c484e580-a04a-11eb-9ace-65f594bfe416.png)

**Comment by DanielLyleWilliamWarren** [comment]
Merged, closing issue.
