### ISSUE TITLE
Add support for box-and-whisker plots

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#418]
# **User story**

As a nutritionist, I want to explore MN data in a box-and-whisker plot, so I can get a broader understanding of it.

## Summary

A box-and-whisker plot on the biomarker data page showing MN concentration in different regions.

[Figma prototype](https://www.figma.com/proto/swhv1D7WScZwDE5KKYkkaE/BMGF-Maps?node-id=1767%3A2426&viewport=-4666%2C-4960%2C0.269345760345459&scaling=contain&page-id=0%3A1&hide-ui=1)

## Wireframe

![image](https://user-images.githubusercontent.com/72566636/115901975-ca6b3400-a459-11eb-875c-2e7f3a9f02e6.png)

## Location

Biomarker data page

![image](https://user-images.githubusercontent.com/72566636/116215428-95076480-a73f-11eb-8a26-bb06f31c87cb.png)

## Related issue 

The box-and-whisker plot is part of:

#420 

## Resources

Sample data available in MS Teams (WP4)

# **Acceptance Criteria**

*   [ ] Box-and-whisker plot is visible on the biomarker data page
*   [ ] Plot shows the region data
*   [ ] (Bonus points) Plot shows deficiency threshold and threshold for abnormal values
*   [ ] (Bonus points) Plot can be maximised for a closer view
*   [ ] (Bonus points) You can toggle Outliers on/off

**Comment by jyou-bgs** [comment]
The data for the ChartJS boxplot plugin can be provided as an array of 5 values in the following format:
**[Min, Lower quartile(Q1), Median, Upper quartile(Q3), Max]**
![boxplot_chartjs](https://user-images.githubusercontent.com/72548880/115727560-9a4d6380-a37b-11eb-8d2f-dc960ca5e05e.png)

So, for the following values it will construct this plot: **[10, 20, 30, 40, 50]**
![image](https://user-images.githubusercontent.com/72548880/115728618-8d7d3f80-a37c-11eb-92d8-c772a33713c6.png)

It's also possible to provide multiple data values for the same plot and the plugin will calculate the statistical values on-the-fly. So, for **[10, 20, 30, 40, 50, 15, 25, 35, 45, 55]** the following plot is generated:
![image](https://user-images.githubusercontent.com/72548880/115729567-6c691e80-a37d-11eb-9c77-82864b154a5e.png)

And these are the values calculated by the plugin:
![boxplot_chartjs_stat](https://user-images.githubusercontent.com/72548880/115730058-df729500-a37d-11eb-996a-e500a3d559cf.png)

It would be good if the API can provide an array of these value for each of the regions so for our chart example the Regions, Central, North, South, South East and West the data could have the following format (array of arrays):
**[[10, 20, 30, 40, 50],[10, 20, 30, 40, 50],[10, 20, 30, 40, 50],[10, 20, 30, 40, 50],[10, 20, 30, 40, 50]]** 

We also need to return the **Deficiency Threshold** and **Threshold for abnormal values.**

**Comment by bgsandan** [comment]
Hi @jyou-bgs this looks great thanks.  One question, how does the plugin deal with plotting/displaying outlier values?

**Comment by jyou-bgs** [comment]
I haven't got the displaying of outliers working yet although it does do it - the online examples and documentation is a bit sketchy. The outliers will look something like this and it's possible to control the colour and radius for styling:
![image](https://user-images.githubusercontent.com/72548880/115836116-0200be80-a40f-11eb-84a8-7f2133801000.png)
I've implemented the toggle switch for the outliers so just need to get them to show.

**Comment by jyou-bgs** [comment]
To display outliers we have to use the correct constructor/interface for the  ChartJS boxplot plugin as follows:

```
plotData =  
  { 
      min: 10, 
      q1: 20,
      median: 30, 
      q3: values: 40,
      max: values: 50,
      outliers: [2,5,7,9,55,74,97,...]  // supply an array of numbers
  }
```

See line 644 in `biomarkerStatus.component.ts`  https://github.com/micronutrientsupport/micronutrient-support-tool/blob/develop/src/app/pages/quickMaps/pages/biomarkers/biomarkerStatus/biomarkerStatus.component.ts which currently generates random values to populate the plots.
