### ISSUE TITLE
Data source drop down in the sidebar for biomarker data

### ISSUE THREAD

**Issue by pautva** [micronutrientsupport/micronutrient-support-tool#419]
# **User story**

As a nutritionist, I want to use the best data source for marker data.

## Summary

When biomarker data is selected and age-gender group is selected, the user should be able to select a data source available. 

If only one data source is available, it should be selected automatically.

If not data source is available, an error message should be displayed.

[Figma prototype](https://www.figma.com/proto/swhv1D7WScZwDE5KKYkkaE/BMGF-Maps?node-id=1767%3A2426&viewport=-4666%2C-4960%2C0.269345760345459&scaling=contain&page-id=0%3A1&hide-ui=1)

## Wireframe

Sidebar
![szoter_annotated_image (2)](https://user-images.githubusercontent.com/72566636/115058305-0b54cd00-9edd-11eb-91af-50156e59a432.jpeg)

No data source available
![image](https://user-images.githubusercontent.com/72566636/115145284-ad44f880-a048-11eb-9342-dee2bba7aa49.png)

# **Related Issues**

## **Front-End**

#416 Add age-gender group dropdown to sidebar when biomarker selected

## **API**

???

## **Database**

???

# **Acceptance Criteria**

*   [ ] When biomarker data and age-gender group is selected, available data sources are loaded in the drop down
*   [x] User can select one of the available data sources
*   [x] If only one source is available, it is selected by default
*   [x] If no source is available, an error message is displayed.

**Comment by jon571** [comment]
Is "Data Source" different from the current "Micronutrient data options"?

**Comment by pautva** [comment]
We have the same dropdown for "Diet Data", but I guess the options in the dropdown for "Biomarker Data" would be different since the data would be coming from a different survey.

**Comment by jon571** [comment]
So we need to change the current "Micronutrient data options" drop-down to "Data Source", and use a different source for the options when "biomarker data" is selected?

**Comment by bgsandan** [comment]
Hi @jon571 Yep, I'm happy for it to use the same dropdown component, routing etc. if that is easier.  The 'Micronutrient Data Options' dropdown could be renamed to something more generic e.g. 'Data Source'.  The key difference will be as @pautva says that the data that populates it will be different.  In the same way that the current diet dropdown calls a different `data-sources` endpoint for `country/household` level diet data, I envisage a third variant of the route for `biomarker` which will return the same structure of data source name and ID which can be used for subsequent requests from the biomarker page cards

**Comment by jon571** [comment]
So an example call for data sources with diet data is:
https://devapi.micronutrient.support/data-source/BEN/diet

If biomarker is selected the current callout is (which brings back data):
https://devapi.micronutrient.support/data-source/BEN/biomarker

I expect that the age-gender selection will need to be added to this, once it is implemented on the API.

**Comment by rbroth** [comment]
Does "data source" refer to the name of the survey that interviewed the household members? If so, it would slot in nicely with our current data architecture. Or does "data source" refer to something else? Do we have example data for biomarker data sources?

**Comment by bgsandan** [comment]
Hi @rbroth yes, it is exactly that.  So basically analogous to e.g. the `fct_source_id` table.  In the same way as for the diet data we will want for Quick MAPS to select the 'best' dataset for the chosen country e.g. the 2018 country X biomarker survey over the 2016 one.  But to support selection of other datasets in the future.  Make sense?

**Comment by rbroth** [comment]
Makes sense. Would it make sense to keep the biomarker surveys and the food consumption surveys in the same table (`survey`)? So far my mental model has had quite a bit of overlap in the food consumption surveys and the biomarker surveys, as in "Good morning, could you please tell me your age, your income, and what you've eaten in the last 24 hours? Also, please pee in this cup." With both referring to households with household members.

**Comment by bgsandan** [comment]
Hi @rbroth.  I'm not opposed to them both being in the same table though of course would need a column flag to indicate and filter on the type of survey.

**Comment by jon571** [comment]
@bgsandan @rbroth 
Any progress on the API/database side for this?  The front end is about there so if not I'll move on to another issue.

**Comment by bgsandan** [comment]
Will catch up at the stand-up this morning where we are with the data architecture/test data.  Configuring the API routes should then only be a matter of minutes
