### ISSUE TITLE
Add MN status card

### ISSUE THREAD

**Issue by pautva** [micronutrientsupport/micronutrient-support-tool#420]
# **User story**

As a nutritionist, I want to see and compare MN concentration in different regions of the nation.

## Summary

A card showing mean MN concentration on a map, table, bar chart and Download tab.

## Location

Biomarker data page

![image](https://user-images.githubusercontent.com/72566636/116108918-3fce4300-a6ac-11eb-9d65-753931e30db6.png)

### Maps:
1) Prevalence of deficiency
2) Prevalence of excess
3) Concentration data

![image](https://user-images.githubusercontent.com/72566636/116104633-828e1c00-a6a8-11eb-87c5-ee33d400a35b.png)

### Table

1) Prevalence of deficiency
2) Prevalence of excess
3) Combined deficiency and excess
4) Concentration Data

![image](https://user-images.githubusercontent.com/72566636/115901278-df939300-a458-11eb-9494-176cd660e022.png)

<details>
<summary>Tables: Prevalance of deficiency, Prevalance of deficiency (same columns for both)</summary>
<br>

![image](https://user-images.githubusercontent.com/72566636/116106879-668b7a00-a6aa-11eb-86c1-fa84103a1781.png)

</details>

<details>
<summary>Table: Combined deficiency and excess</summary>
<br>

![image](https://user-images.githubusercontent.com/72566636/116106751-4eb3f600-a6aa-11eb-9b17-1802d3291c83.png)

</details>

<details>
<summary>Table: Concentration data</summary>
<br>

![image](https://user-images.githubusercontent.com/72566636/116116540-2bda0f80-a6b3-11eb-8bba-64cbae13c2dc.png)

</details>

<details>
<summary>Table: All characteristics in one table</summary>
<br>

Columns are the same as for the tables above. 

Rows as below:

![image](https://user-images.githubusercontent.com/72566636/116116444-1369f500-a6b3-11eb-8450-79e6cb796126.png)

</details>

### Charts 

1) Prevalence of deficiency
2) Prevalence of excess
3) Combined deficiency and excess
4) Concentration Data

![image](https://user-images.githubusercontent.com/72566636/115869561-f379cd80-a435-11eb-978e-d613376635fa.png)

<details>
<summary>Chart: Prevalence of deficiency and Prevalence of Excess (same structure for the chart)</summary>
<br>

![image](https://user-images.githubusercontent.com/72566636/116109205-7b690d00-a6ac-11eb-99d0-a8dbbf6f0d97.png)

</details>

<details>
<summary>Chart: Combined deficiency and excess</summary>
<be>

We can use the same bar chart as the Monthly Summary Chart in Diet Data. Each bar would have deficient, excess and adequate data for different characteristics.

![image](https://user-images.githubusercontent.com/72566636/116233161-e2410180-a752-11eb-8853-c999d7c5c372.png)

The legend would show colours for deficient, excess and adequate bars. Similar as the Monthly Food chart on the diet page:
![image](https://user-images.githubusercontent.com/72566636/116233267-fdac0c80-a752-11eb-82c5-8ff1757ad452.png)

</details>

<details>
<summary>Chart: Concentration data</summary>
<br>

![image](https://user-images.githubusercontent.com/72566636/116109446-ad7a6f00-a6ac-11eb-8283-750d440261ee.png)

</details>

### Download
![image](https://user-images.githubusercontent.com/72566636/116107415-ed405700-a6aa-11eb-8917-2ef6e8300837.png)

### **Front-End**

*   N/A

### **API**

*   ??

### **Database**

*   ??

## **Acceptance Criteria**

*   [x] Biomarker page has the MN Status card
*   [x] The card heading has this structure - {{MN}} Status in {{Genger-group}}
*   [x] The card has four tabs - map, table, chart and download
*   [x] The card can be moved and resized

### Map
*   [x] You can choose between 3different maps
*   [x] The map shows MN concentration using a colour ramp
*   [x] Map has a lenend
*   [ ] Map has a title above the legend
![image](https://user-images.githubusercontent.com/72566636/116114330-2bd91000-a6b1-11eb-9919-97941231d916.png)

### Table

*   [ ] You can choose data type and a characteristic
*   [ ] Data type dropdown options - Prevalence of deficiency, Prevalence of excess, Combined deficiency and excess, Concentration data
*   [ ] Characteristics dropdown options - Regions, Residence, Age group, Wealth quintiles, All characteristics

### Chart
* [ ] You can explore 4 different charts
* [ ] Deficiency and excess show a simple bar chart
* [ ] Combined deficiency and excess show bar chart with 2 bars for each characteristic
* [ ] Concentration data shows box-and-whisker plot

### Download
* [ ] Options to download Deficiency, Excess, Combined deficiency and excess and concentration data
* [ ] You download Map, Tables, Bar chart and CSV files (CSV is of less importance, could come later)
* [ ] You can read more about each file type (e.g. data formats and what's included in the download)

**Comment by Sveouu** [comment]
@DanielLyleWilliamWarren I think most of the above tasks have been completed, but might want to keep this open until API data is available to test/tweak functionality, or close and create new issue.

**Comment by bgsandan** [comment]
Closing for now.  Will re-evaluate when biomarker data and requirements settled.
