### ISSUE TITLE
Add biomarker data overview card

### ISSUE THREAD

**Issue by pautva** [micronutrientsupport/micronutrient-support-tool#444]
# **User story**

As a researcher, I want to get a quick overview of biomarker data, so that I can decide whether I want to explore this data in more detail

## Summary

A summary card showing key numbers for the age-gender group selection

[Figma prototype](https://www.figma.com/proto/swhv1D7WScZwDE5KKYkkaE/BMGF-Maps?node-id=1767%3A2426&viewport=-4666%2C-4960%2C0.269345760345459&scaling=contain&page-id=0%3A1&hide-ui=1)

## Wireframe

![image](https://user-images.githubusercontent.com/72566636/115868669-b5c87500-a434-11eb-8b6c-688cf3bb6395.png)

## Location

Biomarker data page
![image](https://user-images.githubusercontent.com/72566636/115868726-cb3d9f00-a434-11eb-9b3d-a45a3b41917b.png)

# **Acceptance Criteria**

*   [x] The summary card is visible on the biomarker data page
*   [ ] On the left it shows Nation, Micronutrient, Age group and date of the survey
*   [ ] On the right it shows Deficient, Excess and Adequate numbers
*   [x] The numbers are shown as percentage

**Comment by jon571** [comment]
Do we have an API endpoint to supply the data for this component yet @bgsandan ?

**Comment by jon571** [comment]
Do we know where the year comes from on here and the description component above?  They're currently both hard-coded.

**Comment by bgsandan** [comment]
It is part of the metadata for the data source.  The diet data source API endpoint currently just returns the text name and the ID of the data source.  It looks like we may need to expand that when building the biomarker data source to also have the year as a separate field.

**Comment by jon571** [comment]
Hard-coded values used for the following until they're available on API responses:

year
Deficient value
Excess value
Adequate value

**Comment by bgsandan** [comment]
Closing for now.  Will re-evaluate when biomarker data and requirements settled.
