### ISSUE TITLE
Add Additional Information Card

### ISSUE THREAD

**Issue by pautva** [micronutrientsupport/micronutrient-support-tool#445]
# **User story**

As a data scientist, I want to explore the data in more detail, so I that I can understand it better.

## Summary

A card that lets you explore Descriptive Statistics and other information about Data

[Figma prototype](https://www.figma.com/proto/swhv1D7WScZwDE5KKYkkaE/BMGF-Maps?node-id=1767%3A2426&viewport=-4666%2C-4960%2C0.269345760345459&scaling=contain&page-id=0%3A1&hide-ui=1)

## Wireframe

![image](https://user-images.githubusercontent.com/72566636/116117183-de11d700-a6b3-11eb-8977-2fa32b97a180.png)

## Location

Biomarker data page

# **Acceptance Criteria**

*   [x] The biomarker page has an additional information card
*   [x] The card has three tabs - Descriptive statistics and More information + Download tab
*   [x] Descriptive statistics has and bar chart and a table
*   [ ] (TO BE UPDATED) More information card will have some text and links to other resources

**Comment by DanielLyleWilliamWarren** [comment]
> @DanielLyleWilliamWarren can this issue be closed or is there anything to be added i.e. "some text and links to other resources"?

I think best to wait, hopefully @pautva or @bgsandan will update the issue when the figma has been updated with the changes to the card.

**Comment by bgsandan** [comment]
Closing for now.  Will re-evaluate when biomarker data and requirements settled.
