### ISSUE TITLE
Update Summary card contents

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#477]
**Baseline Page**

*   [x] In Baseline page, remove "Baseline assumption" (this may have knock-on API implications for the data that feeds the business as usual estimate card beneath this one)

![](https://user-images.githubusercontent.com/39411049/116673322-29b9ce80-a99b-11eb-987f-b3987ac1f40b.png)

*   [x] Replace the extended text with placeholder text for now
*  [x] add anew BaselineDescriptionDialog and replace both text fields with Lorem Ipsum placeholder text for the time being

**Projections Page**

![](https://user-images.githubusercontent.com/39411049/116673527-6ab1e300-a99b-11eb-9b44-15e80c670295.png)

*   [x] Remove Data level
*   [x]  Add a closing button to both description dialogs

**Comment by Sveouu** [comment]
merged into develop 30/04
