### ISSUE TITLE
Investigate data download as CSV

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#478]
Similar to the ability to download charts as images we want the ability to download the tabular data in a csv format.

This could be facilitated as part of the API, but as the data is already loaded to the front-end to populate the angular material tables, is there any way of instigating the download from the client?

**Comment by Sveouu** [comment]
- [ ] Monthly food Group
- [ ] Top Food Source
- [ ] Household Histogram
- [ ] Projected Availability
- [ ] Projected Food Source
- [ ] Biomarker Info
- [ ] SubRegion Data item --> Map json data

**Comment by Sveouu** [comment]
Csv data download refactored  by JS.
The following require refactoring once live API data is available
**Biomarker Info, Household Histogram, Sub Region Data Item**
