### ISSUE TITLE
Dynamic thresholds for choropleth bins

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#483]
![](https://user-images.githubusercontent.com/39411049/120285282-fe394500-c2b4-11eb-8b7d-7e4c8a54c4c8.png)

Current bins ranges are hardcoded (?) meaning most data is rendered as the same bin.

The tool should allow the bin ranges, (and number of bins?) to be provided as part of the API response.

### Acceptance Criteria

*    [x]  Bin ranges can be set dynamically when the data is fetched/rendered
*    [x]  Number of bins can be set dynamically when the data is fetched/rendered
*    [x]  Appropriate data structure for bins parameters is defined to be implemented in API
*    [ ]  (Bonus): UI to allow user to alter bin parameters as well as colour ramp

**Comment by bgsandan** [comment]
This may already be mainly supported.  I'm sure @Sveouu and @DanielLyleWilliamWarren will shout up if so :smile:

**Comment by DanielLyleWilliamWarren** [comment]
Myself and @Sveouu have been doing some investigations this morning and as soon as the API is delivering the threshold and absolute bin values then they will be dynamically applied. 

Allowing the custom alteration of the bin values increases the complexity quite significantly, I think this requires a discussion with yourself and @pautva if we want to invest developer time in developing that capability.

**Comment by bgsandan** [comment]
Happy to shelve user defined bin values.  Do you have an example data structure for the API data to deliver the bin values in?

**Comment by DanielLyleWilliamWarren** [comment]
{
   binValues: {
      threshold: Array<number>,
      absolute: Array<number>,
   }
}

Would be ideal

**Comment by DanielLyleWilliamWarren** [comment]
`
  binValues: {
    threshold: Array<number>;
    absolute: Array<number>;
  };
`

**Comment by bgsandan** [comment]
So for the above chart would it be:

`binValues: { threshold: [ 0, 10, 50, 100, 250, 500, 1000, 1500 ], absolute: ....`?

Any limitations on number of bin values?

**Comment by bgsandan** [comment]
Implemented in #684
