### ISSUE TITLE
Projection summary card updates

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#484]
*   [x] Estimate value should be rounded to rounded to 3 significant figures.
*   [x] Total value should be rounded to rounded to 3 significant figures.
*   [x] Difference value should be rounded to rounded to nearest integer
*   [x] Difference info button value should be rounded to rounded to 3 significant figures.
*   [x] Difference info button should state that data is rounded to 3 significant figures e.g. "12800 mg per day (3.s.f)"

![](https://user-images.githubusercontent.com/39411049/120287213-f7abcd00-c2b6-11eb-9ad5-0b3d561a7e35.png)

**Comment by jon571** [comment]
This is in the "Baseline Estimate" component and shows on the baseline page when the micronutrient is "isInImpact".  Just thought I'd point this out as the issue specifically mentions "projections"., in case it shouldn't show on the baseline page.

**Comment by bgsandan** [comment]
Ah good spot.  To clarify the comments above should apply to this card on both the baseline estimate card on `/diet/baseline` and the projections page `/diet/projection`.  The visibility of the cards is correct.  Haven't looked at the code recently to know if they are the same or two very similar components :smile:

**Comment by jon571** [comment]
@bgsandan 
Will the projection summary endpoint always return a single result? Just trying to simplify some of the code.

**Comment by bgsandan** [comment]
The tool will only display a single result.

The endpoint (in the updated v2 API) is likely to look something like:

`GET /diet/projection/summary?countryId=XXX&micronutrientId=YYY&scenarioId=ZZZ` where the query params are technically optional 

So another consumer of the API could request multiple summaries, but as the tool will be able to specify all 3 query params it will always return a single result.  

Does that answer the question?

**Comment by jon571** [comment]
Actually there are two components here (one for projection one for baseline), that look exactly the same, apart from the link at the bottom baseline one taking you to projection.
Any reason to think that they will ever be different apart from the link @bgsandan ?

**Comment by bgsandan** [comment]
I won't say "never" but certainly in the current plans/designs I see no reason for them not to be the same component (with an optional link at the bottom)
