### ISSUE TITLE
Add info tab to all cards, with info button in title bar

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#485]
*   [x] Each card (chart, map etc.) should have an info button as part of its title bar
*   [x] Each card will have an info tab
*   [x] Info tab will briefly explain what the visualisation is showing.  Text TBC
*   [x] For now use placeholder and/or Lorem Ipsum text, but each card should have its own description text

_Updated to reflect discussions in the comments_

**Comment by Fuhji** [comment]
Couple Qs @bgsandan @pautva :

- How long would these descriptions be (approx)? Tooltips work well for short sentences but if the text is verbose it will be a less suitable way of explaining
- Its possible to activate the hover on mobile with a long tap but this is not as well-known so mobile users may miss this
- Based on the above two thoughts, another option is an ℹ️ icon on the toolbar header which either: 1) opens dialog with more info, 2) changes card content to a more details 'about this card' tab

**Comment by bgsandan** [comment]
I wasn't envisaging more than a couple of sentences as in your example screenshot.

The mobile point is a very valid one

I had thought about the extra tab in the card.  I was concerned we may end up with too many tabs.  Then again it does mean the text length stops being an issue.

I like the :information\_source: icon suggestion.  Not sure which is best out of modal/tab.  I guess the tab keeps the context so maybe unless @pautva has any other insight I'd go for the extra tab with an info button in the header to jump to it

**Comment by Fuhji** [comment]
I'll go with tab for now as any content could be ported to a dialog just as easy, but reducing popups seems a safer bet.

**Comment by Fuhji** [comment]
MR #491 ready to close this issues @bgsandan if complete for now.

**Comment by bgsandan** [comment]
Looks great! 👍
