### ISSUE TITLE
Projections Food source card updates

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#495]
![](https://user-images.githubusercontent.com/39411049/120445715-cdbedd00-c380-11eb-83f0-4135e1d90080.png)

*   [x] Update card height to contain chart plus selection boxes without scroll
*    [x]  Y-axis label "\<Micronutrient> in mg/capita/day"
*    [x]  3.s.f for values in hover (Update from @Fuhji: set SF to match digit length)
*    [x]  Add:question:hover next to dropdown for "commodity" / "food group" to indicate the difference between the two
*   [x] In text "Food sources for \<Micronutrient> grouped by", convert micronutrient name to lower case

![](https://user-images.githubusercontent.com/39411049/120446295-53428d00-c381-11eb-8089-37eaedae1565.png)

*    [x]  Select 2010 by default in table view so some data is displayed when viewing card for the first time
*   [x] Update "Name" column name to either "Commodity name" or "Food group name" depending on selection
*   [x] Update "value" column name to "\<Micronutrient> in mg/capita/day"

**Comment by bgsandan** [comment]
> @bgsandan Question about 3 significant figures:
> 
> input value: 30666.801
> using Angular `value.toPrecision(3)` :
> Output 3 s.f: 3.07e+4
> 
> Presuming this is not what you are wanting to display?

Not really.  More like 30700.  @jon571 did make a 'significant figures' pipe in #484 which might be useful assuming Angular will let you use it in this context?

**Comment by bgsandan** [comment]
> Question 2: is there text I can use within the tooltip to explain difference between commodity and food group?

Not currently, it's on the list of requested text :)

**Comment by Fuhji** [comment]
> > @bgsandan Question about 3 significant figures:
> > input value: 30666.801
> > using Angular `value.toPrecision(3)` :
> > Output 3 s.f: 3.07e+4
> > Presuming this is not what you are wanting to display?
> 
> Not really. More like 30700. @jon571 did make a 'significant figures' pipe in #493 which might be useful assuming Angular will let you use it in this context?

Yes I can use @jon571 's pipe for this but the hard set 3 s.f. means that larger values are converted to e+. Examples:

Thousands
![image](https://user-images.githubusercontent.com/4210022/120467543-31083980-c398-11eb-95b4-554b5558106c.png)

Hundreds
![image](https://user-images.githubusercontent.com/4210022/120467574-3796b100-c398-11eb-8001-6828681bbe6d.png)

**Comment by Fuhji** [comment]
UPDATE to Sf
digit length used for precision

4 sf
![image](https://user-images.githubusercontent.com/4210022/120469870-d1f7f400-c39a-11eb-9589-da891edb41b7.png)

3 sf
![image](https://user-images.githubusercontent.com/4210022/120469950-e5a35a80-c39a-11eb-951c-fbee88e6b56c.png)

2 sf
![image](https://user-images.githubusercontent.com/4210022/120470038-ff44a200-c39a-11eb-886d-67576fd76574.png)

**Comment by Fuhji** [comment]
closed with MR #498
