### ISSUE TITLE
Create scenarios page

### ISSUE THREAD

**Issue by pautva** [micronutrientsupport/micronutrient-support-tool#499]
# Isue Status

![status-develop](https://user-images.githubusercontent.com/72566636/120615664-6a9c7b80-c450-11eb-8b4d-231deaaf1631.png)

# Summary
The scenarios page will be accessible from Diet Data view

[Figma prototype](https://www.figma.com/proto/swhv1D7WScZwDE5KKYkkaE/BMGF-Maps?node-id=1767%3A2426&viewport=-4666%2C-4960%2C0.269345760345459&scaling=contain&page-id=0%3A1&hide-ui=1)

# Wireframe
![Scenarios](https://user-images.githubusercontent.com/72566636/116717209-8edbe700-a9d0-11eb-8762-eaba8d5cea74.png)

# Description

The page will hold 3 components:
* Summary Card #500
* Options #501
* Data visualisation card #502

# Related issues

![gloomap_002be100](https://user-images.githubusercontent.com/72566636/120505029-85251500-c3bc-11eb-8a6a-c54fb95bbb3c.png)

# Acceptance criteria

- [x] Scenarios page exists and it can be accessed from the Diet Data page

**Comment by jon571** [comment]
I think this issue may be complete @DanielLyleWilliamWarren
