### ISSUE TITLE
Scenarios - Scenario options

### ISSUE THREAD

**Issue by pautva** [micronutrientsupport/micronutrient-support-tool#501]
# Figma prototype status

![status-develop](https://user-images.githubusercontent.com/72566636/120617353-ed720600-c451-11eb-9fd5-821aebb9f77b.png)

# **User story**

As a policymaker, I want to explore various dietary change scenarios so I can make evidence-based recommendations.

# Summary
The card will allow you to toggle between:

1. Food item composition
2. Food item consumption
3.  Food item comparison

![image](https://user-images.githubusercontent.com/72566636/120504796-573fd080-c3bc-11eb-9c0f-e323ed9be1f8.png)

The scenario details are addressed in separate issues.

[Figma prototype](https://www.figma.com/proto/swhv1D7WScZwDE5KKYkkaE/BMGF-Maps?node-id=1767%3A2426&viewport=-4666%2C-4960%2C0.269345760345459&scaling=contain&page-id=0%3A1&hide-ui=1)

# Location

Diet Data > Explore Simple dietary change scenarios

Part of scenarios page:
#499 

Scenario options:
* Composition #506 
* Change #507 
* Comparison #508 

# Reference

<details>
<summary>Other Scenarios issues</summary>
<br>

![gloomap_002be100](https://user-images.githubusercontent.com/72566636/120618179-ba7c4200-c452-11eb-86d8-919e5051f0a7.png)

</details>

# Acceptance criteria

* [x] You can toggle between different scenarios

**Comment by jon571** [comment]
@bgsandan  Are these controls to have query linked params that allow pre-population from a link?

**Comment by bgsandan** [comment]
If we can make it sensibly work it would be nice please 😊

**Comment by jon571** [comment]
When switching between these options, will the previously selected food items stay selected?

**Comment by bgsandan** [comment]
As in stay selected so you could switch back to a previous option and see your previous selection?

I'm happy for switching between the different modes "Composition", "Consumption", "Food Item" to wipe out the previous selection so when you switch mode you get a fresh empty selection (ideally with an 'are you sure you want to do this' type dialog/warning first).  I assume that would still be simpler than trying to maintain/store all permutations?

Given that if params are part of the URL a user could save/share a scenario to get back to it, don't think they need to persist between mode changes.

Happy to hear other thoughts/opinions though :smile:

**Comment by jon571** [comment]
The "food items" are consistent between the three modes, so we could keep them, but persisting those without the values might seem inconsistent.

That would mean it's all or nothing, and if you're happy with nothing (initially), then so am I. :-)

**Comment by pautva** [comment]
I agree with Andy that some warning message would be useful in case the selection gets deleted. If somebody adds more than 10 items and then loses their progress, that could be frustrating :)

If we have an option to save a URL with query params, we could add "Bookmark scenario" button next to "Share Page".

**Comment by jon571** [comment]
We'll probably need to alert on changing the option and have a "canDeactivate" route guard too then.

**Comment by jon571** [comment]
> I agree with Andy that some warning message would be useful in case the selection gets deleted. If somebody adds more than 10 items and then loses their progress, that could be frustrating :)
> 
> If we have an option to save a URL with query params, we could add "Bookmark scenario" button next to "Share Page".

There's certainly the potential to frustratingly lose a lot of configuration there!

Is it not likely that they will want to change from "Composition" to "Consumption" with the same food items selected?

**Comment by bgsandan** [comment]
@LouiseAnder see above conversation - what are your thoughts on the likelihood of a user wanting to switch from "Composition" scenario to "Consumption" scenario and maintain the same list of food items?

**Comment by LouiseAnder** [comment]
this is a good question - I am also concerned that if we are allowing a large number of simultaneous changes we support the user diverging from anything vaguely realistic / achievable in a food system.  I tend to think that Andy's suggestion where they are (with prior warning) wiped, keeps it very clear what the user is altering too. Like that there is some URL/bookmark way of returning to scenarios though. 

Not sure if this should be a separate issue, but will these permutations be captured somewhere on any downloadable output @bgsandan ?

**Comment by jon571** [comment]
Any idea how the API will deliver the food groups and items?  Will it be a single call for everything, given the micronutrient, with the response being an array of food groups with a nested food items?

**Comment by bgsandan** [comment]
Open for discussion/requests! Assuming that sort of structure works for you that is probably more efficient than a separate call to get the food items for each food group?

**Comment by jon571** [comment]
> Open for discussion/requests! Assuming that sort of structure works for you that is probably more efficient than a separate call to get the food items for each food group?

Would this be dependant on anything or more like a dictionary call (no params).

**Comment by bgsandan** [comment]
Good question.  The food groups/food items probably more of dictionary. The call to get "current" value will need to pass either the consumption data source id or composition source id depending on the mode along with the selected fooditem. Make sense?

**Comment by jon571** [comment]
> > Good question. The food groups/food items probably more of dictionary. The call to get "current" value will need to pass either the consumption data source id or composition source id depending on the mode along with the selected fooditem. Make sense?
> 
> Might it make sense to have these "current" values as part of the "food item" object, as they're not going to change.

Ignore this.  :-)

**Comment by jon571** [comment]
I'm currently trying to get some api endpoints and mock data in for this.

**Comment by jon571** [comment]
> Good question. The food groups/food items probably more of dictionary. The call to get "current" value will need to pass either the consumption data source id or composition source id depending on the mode along with the selected fooditem. Make sense?

Where are the consumption data source id and composition source ids obtained from?

**Comment by bgsandan** [comment]
The data-source endpoint called to populate the bottom select option in the sidebar.  e.g. https://devapi.micronutrient.support/data-source/ZAF/diet

**Comment by jon571** [comment]
> The data-source endpoint called to populate the bottom select option in the sidebar. e.g. https://devapi.micronutrient.support/data-source/ZAF/diet

So they're not different things, just the data source id (as opposed to "consumption data source id" and "composition source id")?

**Comment by bgsandan** [comment]
Sorry, caused confusion yesterday with inaccurate terminology when typing on my phone!

In "Composition Change" mode, there will be an API to get the 'Current composition' value.  That will take as input the `compositionDataId` parameter from the above URL and an id for the fooditem selected e.g `/diet/scenario/composition/?foodItem=123&compositionDataId=XYZ` (url TBC)

In "Consumption Change" mode, there will be an API to get the 'Current consumption' value.  That will take as input the `consumptionDataId` parameter from the above URL and an id for the fooditem selected e.g `/diet/scenario/consumption/?foodItem=123&consumptionDataId=XYZ` (url TBC)

Is that clearer?  Happy to chat otherwise :)

**Comment by jon571** [comment]
@Sveouu It's probably not completely obvious from the conversations on this issue that this task really is just selecting the mode (consumption/composition/food item), and there are other issues for the options associated with those selections.

I hope I haven't confused matters too much by starting conversations here that should maybe have been on other issues.  I know that @Fuhji is looking at the composition options task #506, so I just wanted to ensure that there isn't any duplication of effort.

**Comment by jon571** [comment]
@bgsandan @pautva

Not really associated with this task but as it spans all three modes it seems the best place for it.

Can we tweak the UI for the options panel so that when you "Add Food Item" it makes the previously selected food items un-editable?

Otherwise updating the available options in all of the active selects will be complicated.  The scenario value can still be editable.

**Comment by bgsandan** [comment]
As in:

1.  User selects a food item using the dropdowns
2.  Tool loads the value for 'current consumption' (or composition etc)
3.  User can then update the scenario values
4.  At this point user can change the select box as it isn't 'locked in'
5.  User clicks "Add Food item" to add another option
6.  The select boxes for selection no. 1 are locked so they can't change that food item but can still edit the scenario value
7.  Steps 2-4 apply to selection no. 2

?

In which case i think that is fine.

With multiple fooditems we may want to be able to delete/remove one of them though..  Happy to allow removing only the latest one (thus 'unlocking' the selection box for the previous item) if that is easier and fits with the above model though

**Comment by jon571** [comment]
Should be:
> 7. Steps **1**-4 apply to selection no. 2

I don't see a problem with being able to remove **any** of the previous rows.

The "All" option will complicate matters, and will only be available if nothing from that group has previously been selected.

**Comment by jon571** [comment]
On the subject of the "ALL" option, I'm working on the assumption that that will need expanding to a full group of individual food item selections for the API call and that there won't be a shortcut way to send a group id instead.  Is that correct.

**Comment by bgsandan** [comment]
Sending a full group of id's will certainly work.  Though we could look at an endpoint that takes a group id if we think it would be useful

**Comment by jon571** [comment]
> Sending a full group of id's will certainly work.  Though we could look at an endpoint that takes a group id if we think it would be useful

It would have to be the same endpoint since they might have selected item A from group 1 and All from group 2.

I'll still assume expanding the "ALL" to include all food item IDs.
