### ISSUE TITLE
Scenarios - Card component for data viz

### ISSUE THREAD

**Issue by pautva** [micronutrientsupport/micronutrient-support-tool#502]
# Figma prototype status

![status-develop](https://user-images.githubusercontent.com/72566636/120617353-ed720600-c451-11eb-9fd5-821aebb9f77b.png)

# Summary

Card for visualising scenarios.

The card will include three tabs:
* #503 **Map**
* #504 **Table**
* #505 **Download**

[Figma prototype](https://www.figma.com/proto/swhv1D7WScZwDE5KKYkkaE/BMGF-Maps?node-id=1767%3A2426&viewport=-4666%2C-4960%2C0.269345760345459&scaling=contain&page-id=0%3A1&hide-ui=1)

# Wireframe
![image](https://user-images.githubusercontent.com/72566636/116725244-9489fa80-a9d9-11eb-8b37-6e72740a49e3.png)

# Location

Diet Data > Explore Simple dietary change scenarios

Part of scenarios page:
#499 

Related issues:
#503 Map
#504 Table
#505 Download

# Reference

<details>
<summary>Other Scenarios issues</summary>
<br>

![gloomap_002be100](https://user-images.githubusercontent.com/72566636/120618179-ba7c4200-c452-11eb-86d8-919e5051f0a7.png)

</details>

# Acceptance criteria

- [x] The card exists on Scenarios page 
- [x] The card has 3 tabs

**Comment by jon571** [comment]
@bgsandan are we happy that there will just be one card and that the data that we use for all three options will be easily interchangeable?

If the data is completely different, involving separate api calls, it might be easier to have three similar but separate cards.

**Comment by bgsandan** [comment]
The output data structures will be the same, though likely a separate API call for each of the three modes.  Visualisation/presentation will also be largely the same though some titles/labels may change.

Happy for it to be 3 similar cards if that makes more sense

**Comment by jon571** [comment]
If the responses from the API will be the same structure, then I think we should try to keep it as the one component.  If it becomes too messy with switches and if elses we can always look at improving it.

**Comment by jon571** [comment]
I reckon this issue is done too, as the criteria are met.  This doesn't mean that the component is finished, as it might absorb data retrieval code etc. that are common to all of the tab content components.

**Comment by jon571** [comment]
It actually has 4 tabs as there is an "About" tab too :-)

**Comment by jon571** [comment]
@bgsandan  
Will there be three endpoints for retrieving the data for the three modes then, with the responses being similarly formatted?
GeoJson? to cater for the region geography?

**Comment by jon571** [comment]
Or would it make sense to have another endpoint for region geography, so that it doesn't keep getting returned in multiple responses?  The response for the country geography is 1.6Mb but at least we only get that once.

**Comment by jon571** [comment]
> Or would it make sense to have another endpoint for region geography, so that it doesn't keep getting returned in multiple responses? The response for the country geography is 1.6Mb but at least we only get that once.

This is only 45kb though, so maybe sub-regions aren't so bad:
https://devapi.micronutrient.support/diet/household/geojson/MWI/Fe/1/3

**Comment by bgsandan** [comment]
Optimised geopsatial data for regions/countries etc. is something that is being worked on so hopefully will end up with something not too large to come over the wire.  Initial impressions was multiple routes return geoJSON but we could optimise out the sub-regions to a separate route if it becomes an issue

**Comment by bgsandan** [comment]
Yes, responses should be similarly formatted.

*   Consumption mode will take: a composition data source id, a consumption data source id, a fooditem id and a new micronutrient value for that fooditem (or possibly arrays for the last two if multiple fooditems supported)
*   Composition mode will take: a composition data source id, a consumption data source id, a fooditem id, and a new consumption quantity value for that fooditem
*   Comparsion mode will take: a composition data source id, a consumption data source id, a fooditem id and a fooditem id to replace that fooditem with

So largely similar inputs.

Outputs for all 3 should all be similarly formatted also

**Comment by jon571** [comment]
Hi @bgsandan.
For the mock diet change data I thought I'd just copy and change some of the "sub-region-results_original.json" file, where the features look like this:
```
{
    "id": 27,
    "country_name": "Malawi",
    "geometry": {
      "type": "Polygon",
      "coordinates": [
...
      ]
    },
    "country_id": "MWI",
    "subregion_name": "Thyolo",
    "subregion_type": "District",
    "mn_absolute": 1525,
    "mn_absolute_unit": "mg",
    "mn_threshold": 45,
    "mn_threshold_unit": "%",
    "households_surveyed": 91
  },
``` 

I thought I'd add something like a "before_val" and an "after_val".

I'm not sure if there will need to be some properties on the response like for the legend, like:
- max_val
- min_val
- thresholds
- units
Or whether these can be worked out in the front-end from what we already have or by sifting through the values.

Does that sound OK or am I way off?

**Comment by bgsandan** [comment]
Not far off :)

The Baseline supply will be by definition the same data as the previous tab so for the left hand map it could be fetched from the same url as the baseline screen (which is likely cached if not navigating directly to that page).  Then the scenario map can be its own call to an API endpoint which will return the exact same structure as your sample with the new data from the scenario.  Then you only need to call the API and re-draw the left hand map rather than both when the scenario options are tweaked.

Work for you?

**Comment by jon571** [comment]
> Not far off :)
> 
> The Baseline supply will be by definition the same data as the previous tab so for the left hand map it could be fetched from the same url as the baseline screen (which is likely cached if not navigating directly to that page).  Then the scenario map can be its own call to an API endpoint which will return the exact same structure as your sample with the new data from the scenario.  Then you only need to call the API and re-draw the left hand map rather than both when the scenario options are tweaked.
> 
> Work for you?

I think so.  Is it the absolute values that are used here then?

Mentioning @DanielLyleWilliamWarren since he's looking at the maps. #503

So we'll probably pass a baselineData SubRegionDataItem and a scenarioData SubRegionDataItem through from the ComparisonCardComponent to the map/table/download components then.
