### ISSUE TITLE
Scenarios - Consumption change

### ISSUE THREAD

**Issue by pautva** [micronutrientsupport/micronutrient-support-tool#507]
# Figma prototype status

![status-develop](https://user-images.githubusercontent.com/72566636/120622279-915db080-c456-11eb-9e71-4d3a9204e0a4.png)

# **User story**

As a policymaker, I want to explore how food composition change affects the nutrition in a selected country.

## Location
<details>
<summary> Wireframe for the whole scenarios page</summary>
<br>

![Scenarios](https://user-images.githubusercontent.com/72566636/116717209-8edbe700-a9d0-11eb-8762-eaba8d5cea74.png)
</details>

### Scenario options - Consumption change

Adjust the composition of selected food item(s). 

![image](https://user-images.githubusercontent.com/72566636/116724106-26910380-a9d8-11eb-8091-9432f0a109a2.png)

These options will affect the #503, #504 and #505.

# Location

Diet Data > Explore Simple dietary change scenarios

**Part of scenarios page:**
#499 

**Part of component:**
#501

**Related:**
* Composition change #506 
* Food item comparison #508 

# Reference

<details>
<summary>Other Scenarios issues</summary>
<br>

![gloomap_002be100](https://user-images.githubusercontent.com/72566636/120618179-ba7c4200-c452-11eb-86d8-919e5051f0a7.png)

</details>

# Acceptance criteria

<details open>
<summary> Acceptance criteria</summary>
<br>

- [x] Select Food item group
- [x] Select a food item from a food item group
- [ ] Option to select All items from a food item group
- [x] Display current consumption of the food item in ml/AME/day
- [x] Specify scenario composition by changing value manually
- [x] Increase or decrease the scenario value by 5%
- [x] (NICE TO HAVE) Add multiple food items to a scenario
- [x] (NICE TO HAVE) Remove extra items

</details>

**Comment by jon571** [comment]
I'll put this issue on hold until #506 has been completed, since there is a lot of crossover in functionality.
