### ISSUE TITLE
Scenarios - Food item comparison

### ISSUE THREAD

**Issue by pautva** [micronutrientsupport/micronutrient-support-tool#508]
# Figma prototype status

![status-develop](https://user-images.githubusercontent.com/72566636/120622279-915db080-c456-11eb-9e71-4d3a9204e0a4.png)

# **User story**

As a policymaker, I want to compare different food items so that I can make evidence-based recommendations on food item alternatives.

## Location
<details>
<summary> Wireframe for the whole scenarios page </summary>
<br>

![Scenarios](https://user-images.githubusercontent.com/72566636/116717209-8edbe700-a9d0-11eb-8762-eaba8d5cea74.png)
</details>

### Scenario options - Food item comparison

Replace food item(s) in the diet with another food item(s).

![image](https://user-images.githubusercontent.com/72566636/116724353-78d22480-a9d8-11eb-936b-cb4d1be32c8c.png)

These options will affect the #503, #504 and #505.

# Location

Diet Data > Explore Simple dietary change scenarios

Part of scenarios page:
#499 

Part of component:
#501

#Related:
#506 Consumption change
#507 Food item comparison

# Reference

<details>
<summary>Other Scenarios issues</summary>
<br>

![gloomap_002be100](https://user-images.githubusercontent.com/72566636/120618179-ba7c4200-c452-11eb-86d8-919e5051f0a7.png)

</details>

# Acceptance criteria

<details open>
<summary> Acceptance criteria</summary>
<br>

- [x] Select the food item group and a food item to be replaced
- [x] Select the food item group and a food item to replace it with
- [x] Show the current composition for selected items
- [ ] While no food item is selected, display a message on the map and table to users that scenario details need to be selected first
- [x] (NICE TO HAVE) Add additional food items to replace

</details>

**Comment by jon571** [comment]
I'll put this issue on hold until #506 has been completed, since there is a lot of crossover in functionality.
