### ISSUE TITLE
API endpoint integration record

### ISSUE THREAD

**Issue by jon571** [micronutrientsupport/micronutrient-support-tool#515]
Underlying Data | API endpoint | GUI endpoint class | GUI Live data enabled
------------ | ------------- | ------------- | -------------
?????????? | ???????? | [getAgeGenderGroups](https://github.com/micronutrientsupport/micronutrient-support-tool/blob/develop/src/app/apiAndObjects/api/currentData/getAgeGenderGroups.ts) | FALSE
?????????? | [/data-source/{countryId}/{dataType}](https://devapi.micronutrient.support/explorer/#/DataSourceControllerController/DataSourceControllerController.find) | [getDataSources](https://github.com/micronutrientsupport/micronutrient-support-tool/blob/develop/src/app/apiAndObjects/api/currentData/getDataSources.ts) | TRUE
?????????? | ???????? | [getDataSources](https://github.com/micronutrientsupport/micronutrient-support-tool/blob/develop/src/app/apiAndObjects/api/currentData/getDietarySources.ts) | FALSE
?????????? | ???????? | [getHouseholdHistogramData](https://github.com/micronutrientsupport/micronutrient-support-tool/blob/develop/src/app/apiAndObjects/api/currentData/getHouseholdHistogramData.ts) | FALSE
?????????? | ???????? | [getMonthlyFoodGroups](https://github.com/micronutrientsupport/micronutrient-support-tool/blob/develop/src/app/apiAndObjects/api/currentData/getMonthlyFoodGroups.ts) | FALSE
?????????? | [/projection-total](https://devapi.micronutrient.support/explorer/#/auto/ImpactTotalFoodAvailabilityController.findy) | [getProjectedAvailabilities](https://github.com/micronutrientsupport/micronutrient-support-tool/blob/develop/src/app/apiAndObjects/api/currentData/getProjectedAvailabilities.ts) | TRUE
?????????? | [/projections/commodity/{countryId}/{micronutrientId}/{scenarioId}](https://devapi.micronutrient.support/explorer/#/ProjectionsControllerController/ProjectionsControllerController.findCommodityScenario) [/projections/food-group/{countryId}/{micronutrientId}/{scenarioId}](https://devapi.micronutrient.support/explorer/#/ProjectionsControllerController/ProjectionsControllerController.findFoodGroupScenario) | [getProjectedFoodSources](https://github.com/micronutrientsupport/micronutrient-support-tool/blob/develop/src/app/apiAndObjects/api/currentData/getProjectedFoodSources.ts) | TRUE
?????????? | [/projections/summary/{countryId}/{micronutrientId}/{scenarioId}](https://devapi.micronutrient.support/explorer/#/ProjectionsControllerController/ProjectionsControllerController.findSummary) | [getProjectionSummary](https://github.com/micronutrientsupport/micronutrient-support-tool/blob/develop/src/app/apiAndObjects/api/currentData/getProjectionSummary.ts) | TRUE
?????????? | [/diet/country/geojson/{countryId}/{micronutrientId}/{compositionId}/{consumptionId}](https://devapi.micronutrient.support/explorer/#/CountryIntakeControllerController/CountryIntakeControllerController.findCountryIntakeGeojson) [/diet/household/geojson/{countryId}/{micronutrientId}/{compositionId}/{consumptionId}](https://devapi.micronutrient.support/explorer/#/CountryIntakeControllerController/CountryIntakeControllerController.findSubregionIntakeGeojson) | [getSubRegionData](https://github.com/micronutrientsupport/micronutrient-support-tool/blob/develop/src/app/apiAndObjects/api/currentData/getSubRegionData.ts) | TRUE
?????????? | [/diet/country/top20/{countryId}/{micronutrientId}/{compositionId}/{consumptionId}](https://devapi.micronutrient.support/explorer/#/DietCountryControllerController/DietCountryControllerController.findTop20FoodsCountry) [/diet/household/top20/{countryId}/{micronutrientId}/{compositionId}/{consumptionId}](https://devapi.micronutrient.support/explorer/#/DietCountryControllerController/DietCountryControllerController.findTop20FoodsHousehold) | [getTopFood](https://github.com/micronutrientsupport/micronutrient-support-tool/blob/develop/src/app/apiAndObjects/api/currentData/getTopFood.ts) | TRUE
?????????? | [/projection-scenario](https://devapi.micronutrient.support/explorer/#/auto/ImpactScenarioController.findy) | [getImpactScenarios](https://github.com/micronutrientsupport/micronutrient-support-tool/blob/develop/src/app/apiAndObjects/api/misc/getImpactScenarios.ts) | TRUE
?????????? | [/country](https://devapi.micronutrient.support/explorer/#/CountryController/CountryController.find) | [COUNTRIES Dictionary](https://github.com/micronutrientsupport/micronutrient-support-tool/blob/develop/src/app/apiAndObjects/api/api.service.ts#L46) | TRUE
?????????? | ??????? | [REGIONS Dictionary](https://github.com/micronutrientsupport/micronutrient-support-tool/blob/develop/src/app/apiAndObjects/api/api.service.ts#L51) | FALSE
?????????? | [/micronutrient](https://devapi.micronutrient.support/explorer/#/auto/MicronutrientController.findy) | [MICRONUTRIENTS Dictionary](https://github.com/micronutrientsupport/micronutrient-support-tool/blob/develop/src/app/apiAndObjects/api/api.service.ts#L54) | TRUE
?????????? | ??????? | [FOOD GROUPS/ITEMS Dictionary](https://github.com/micronutrientsupport/micronutrient-support-tool/blob/develop/src/app/apiAndObjects/api/api.service.ts#L64) | FALSE
?????????? | ??????? | [getCurrentComposition](https://github.com/micronutrientsupport/micronutrient-support-tool/blob/develop/src/app/apiAndObjects/api/scenario/getCurrentComposition.ts) | FALSE
?????????? | ??????? | [getCurrentConsumption](https://github.com/micronutrientsupport/micronutrient-support-tool/blob/develop/src/app/apiAndObjects/api/scenario/getCurrentConsumption.ts) | FALSE

**Comment by jon571** [comment]
Hi @bgsandan, @rbroth 

I wanted to record somewhere the connection between underlying data, api endpoint and GUI endpoint class so I'm creating this table here.

There might be a better way and if you have another idea or there's already something then shout up, but I'll continue to populate this in the meantime,

**Comment by jon571** [comment]
Although, I only appear to be able to add and edit comments, not the actual issue :-(

**Comment by rbroth** [comment]
I've upped your repo access to 'maintain', try again

**Comment by jon571** [comment]
Ha, there is no content in these GitHub issues!  Just a title and comments :-)

**Comment by jon571** [comment]
This doesn't keep a history of comment changes so it might not be the best place to keep this info.

**Comment by rbroth** [comment]
I've given you admin rights, see if that's better. I can see a history of comment edits

**Comment by bgsandan** [comment]
I'm not against a docs/notes repo of .md files if that would be better to manage...

**Comment by jon571** [comment]
> I've given you admin rights, see if that's better. I can see a history of comment edits

I was looking in the wrong place.  Can see it now :-)

**Comment by rbroth** [comment]
MD files in the repo would be good. Drawback is that it's a bit more difficult for the scientists to work with- they'd have to tell us the changes and we'd have to copy-paste/write them

**Comment by bgsandan** [comment]
I suspect most files likely to be primarily edited by developers (at least initially). Markdown editing via the GitHub web UI isn't too difficult (and there are chrome extensions that give a WYSIWYG editor on GitHub that converts to md behind the scenes.  Also to give the 'scientists' credit a lot of them work with R-Markdown so it's likely not to be that big a leap...

**Comment by rbroth** [comment]
Makes sense. I was thinking difficult in terms of git commits and branching rather than editing markdown files

**Comment by bgsandan** [comment]
Closing as we have failed to keep this up to date.  API docs and api handler folder in this repo probably a better documentation especially now we should be using live endpoints across the whole app
