### ISSUE TITLE
Update titles and tooltip text in Quick MAPS sidebar

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#537]
![](https://user-images.githubusercontent.com/39411049/132051981-d7387b98-f8cc-48e5-adfd-1c456f795c34.jpeg)

**Geography of interest**

Tooltip text - "Select via dropdown menu or via interactive map"

**MND(s) to explore or compare**

Title text - update to "Nutrients to explore"

Tooltip text - "Nutrients available in the tool database."

**Measure of MND**

Title text - update to "Measure of nutrient deficiency"

Tooltip text - "Select diet proxy or biomarker, if both are available"

**Data source**

Tooltip text - "QuickMAPS will default to the latest available dataset from your choices above"

**Comment by Fuhji** [comment]
In the quickmaps sidebar there is still one tooltip to be updated: Age-gender-group.

**Comment by bgsandan** [comment]
> In the quickmaps sidebar there is still one tooltip to be updated: Age-gender-group.

Cc: @LouiseAnder

**Comment by LouiseAnder** [comment]
Biomarker sidebar:

Tooltip text: 'You can choose from the original biomarker survey demographic groups'
