### ISSUE TITLE
Transition to unified V2 API

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#543]
**API Base URL** - [https://api.micronutrient.support/v2/](https://api.micronutrient.support/v2/)

**API Docs** - [https://api.micronutrient.support/docs/core-data-api/reference](https://api.micronutrient.support/docs/core-data-api/reference)

**Updated routes - Sidebar**

List countries `/countries`

List micronutrients `/micronutrients`

Diet data Sources `/diet/data-sources` (Pass country ID and Micronutrient ID)

Biomarker data sources `biomarker/data-sources` (Pass country ID and Micronutrient ID)

**Update routes - Projections**

![](https://user-images.githubusercontent.com/39411049/132054935-12619853-60c6-4ade-881f-da5b5502cba4.png)

**Update routes - Diet Data**

![](https://user-images.githubusercontent.com/39411049/132055057-2ccccb3c-b307-424a-b691-7cf62b7f8ebb.png)

Monthly foods and household dietary supply routes TBC

**Comment by Fuhji** [comment]
is this complete @jon571  and can be closed?

**Comment by jon571** [comment]
Not quite.  The old route is still being used by one component and I'm working on chopping that stuff out now. :-)

**Comment by jon571** [comment]
API endpoints now utilised:
- ​/diet​/country​/availability
- /diet/country/top-foods
- /diet/data-sources
- /diet/household/availability
- /diet/household/top-foods
- /biomarker/age-gender-groups
- /biomarker/data-sources
- ​/diet​/projections​/commodities
- /diet/projections/food-groups
- /diet/projections/scenarios
- ​/diet​/projections​/summaries
- /diet/projections/totals
- /countries
- /micronutrients

It doesn't look like any other endpoints are available, so I'll leave it here and mark this task as complete.
