### ISSUE TITLE
Add 'more info' modal to baseline summary card

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#546]
As in the projections page.  Need to add a 'more details' modal.

This should utilise data returned from the 'data sources' API route in the sidebar.

![](https://user-images.githubusercontent.com/39411049/132333352-d9ff7779-663a-40c8-b8aa-364674aee6af.png)

Content of modal dialogue:

---

_Extended version of the summary card text explaining matching food composition and consumption data._  cc @LouiseAnder

### Food Consumption Data: \<consumptionDataName>

\<consumptionDataDescription>

![GeoNetwork opensource · GitHub](https://user-images.githubusercontent.com/39411049/132333967-f8eb91c5-cb31-4982-846d-1bae6e86360a.jpeg)

Link:

[https://metadata.micronutrient.support/geonetwork/srv/eng/catalog.search#/metadata/\<consumptionDataMetaDataId>](https://metadata.micronutrient.support/geonetwork/srv/eng/catalog.search#/metadata/<consumptionDataMetaDataId>) - "View metadata record"

### Food Composition Data: \<compositionDataName>

\<compositionDataDescription>

![GeoNetwork opensource · GitHub](https://user-images.githubusercontent.com/39411049/132333967-f8eb91c5-cb31-4982-846d-1bae6e86360a.jpeg)

Link:

[https://metadata.micronutrient.support/geonetwork/srv/eng/catalog.search#/metadata/\<compositionDataMetaDataId>](https://metadata.micronutrient.support/geonetwork/srv/eng/catalog.search#/metadata/<consumptionDataMetaDataId>) - "View metadata record"

**Comment by LouiseAnder** [comment]
just to be sure, you mean the equiv to this? @bgsandan 
![image](https://user-images.githubusercontent.com/65279285/132335677-c0d3fa46-4518-4d82-8cf7-1f4f5334060d.png)

**Comment by bgsandan** [comment]
Yes a popup dialog similar to that one but triggered from:

![](https://user-images.githubusercontent.com/39411049/132335991-031fe565-27d0-481f-bd9e-a50e2279cdba.png)

The popup will include the details about the specific datasets in use as highlighted in the issue above, but may also want an introductory paragraph about methods for joining/matching food consumption/composition data before the list/descriptions of datasets in use.  Make sense?

**Comment by bgsandan** [comment]
Yes a popup dialog similar to that one but triggered from:

![](https://user-images.githubusercontent.com/39411049/132335991-031fe565-27d0-481f-bd9e-a50e2279cdba.png)

The popup will include the details about the specific datasets in use as highlighted in the issue above, but may also want an introductory paragraph about methods for joining/matching food consumption/composition data before the list/descriptions of datasets in use.  Make sense?

**Comment by bgsandan** [comment]
Yes a popup dialog similar to that one but triggered from:

![](https://user-images.githubusercontent.com/39411049/132335991-031fe565-27d0-481f-bd9e-a50e2279cdba.png)

The popup will include the details about the specific datasets in use as highlighted in the issue above, but may also want an introductory paragraph about methods for joining/matching food consumption/composition data before the list/descriptions of datasets in use.  Make sense?

**Comment by jon571** [comment]
@bgsandan is this applicable to both the biomarker and diet data source endpoints?

**Comment by bgsandan** [comment]
@jon571 - yes, although the biomarker data source endpoints will have slightly different fields as there is only one type of data (rather than consumption/composition)

![](https://user-images.githubusercontent.com/39411049/132347974-0c2d9142-d391-4ad9-97e0-1da02d1abbeb.png)

**Comment by bgsandan** [comment]
@jon571 - yes, although the biomarker data source endpoints will have slightly different fields as there is only one type of data (rather than consumption/composition)

![](https://user-images.githubusercontent.com/39411049/132347974-0c2d9142-d391-4ad9-97e0-1da02d1abbeb.png)

**Comment by jon571** [comment]
They're currently called from the same class, and result in the same internal object, so if they deviate we might separate them up in the GUI.

**Comment by bgsandan** [comment]
They are semantically different entities (even if similarly structured) so splitting probably does make sense

**Comment by LouiseAnder** [comment]
Will provide text for each shortly, I think the currently presented data combinations are as follows:

1. Food balance sheet + food composition (these are the national 'diet' overviews)
2.  Household survey consumption + food composition (only Malawi IHS4 consumption loaded currently for this view)
3. Biomarker data (single data table results are drawn from)
does that make sense @jon571 ?

**Comment by LouiseAnder** [comment]
@bgsandan  I had something like this in mind, where [**bold**] represents a separate page (which can be a non-populated bookmark for methods for now) or number or metadata drawn from the database. Is this what you had in mind as well or is this a complication too far regarding the links to D/B?

### Household data (item 2 in the bullet points above)
Sub-national data are presented using a combination of locally relevant food composition data joined to household consumption and expenditure survey recall of consumed food items.

For more information on data cleaning and mathematical methods underlying this view see [**link**]. 

These data represent the [**name of survey, year of survey**] data from [**number**] households. There are [**number**] individual food items which have been joined to composition data from [**FCT1, number; FCT2, number;…FCT_k_, number_k_**]

**Comment by jon571** [comment]
Data should be available in GUI after merging of #575

**Comment by bgsandan** [comment]
Addressed for now by #658
