### ISSUE TITLE
observations

### ISSUE THREAD

**Issue by jon571** [micronutrientsupport/micronutrient-support-tool#568]
![image](https://user-images.githubusercontent.com/59727084/132474391-b8af55b5-e6be-4b31-9a5b-11fc629593c3.png)
1. These values hard-coded on biomarker page

![image](https://user-images.githubusercontent.com/59727084/132474572-d40a7411-06a0-4ab1-9781-44a3ab30b2e7.png)
2. Scenario names hard-coded instead of getting from dictionary.
3. Threshold hard-coded from SSP2, should be from scenario marked as baseline and should have same color as the SSP line?

![image](https://user-images.githubusercontent.com/59727084/132475060-8ccfa797-0b14-48b6-9f21-811eadef34cd.png)
4. Maximize button works but card not working in dialog.

![image](https://user-images.githubusercontent.com/59727084/132475309-098ff2b4-7cd6-4816-b7d9-1da2cefa8f43.png)
5. Maximize button doesn't work.

**Comment by DanielLyleWilliamWarren** [comment]
@bgsandan is there a biomarker endpoint to resolve point 1 on this issue?
