### ISSUE TITLE
Current GUI endpoints using mock data

### ISSUE THREAD

**Issue by jon571** [micronutrientsupport/micronutrient-support-tool#576]
Current GUI endpoints using mock data:

- ~~Dietary sources - Doesn't appear to be used~~ REMOVED
- Household Histogram data - National overview card
- Monthly food groups - Monthly food card

- Current composition - Dietary change page
- Current consumption - Dietary change page
- Diet change composition - Dietary change page
- Diet change consumption - Dietary change page
- Diet change food items - Dietary change page

There are also other parts of the code that mock their own data.  Here's a non-exhaustive list:
- https://github.com/micronutrientsupport/micronutrient-support-tool/blob/develop/src/app/pages/quickMaps/pages/biomarkers/biomarkerInfo/biomarkerInfo.component.ts#L152
- https://github.com/micronutrientsupport/micronutrient-support-tool/blob/develop/src/app/pages/quickMaps/pages/biomarkers/biomarkerStatus/biomarkerStatus.component.ts#L210
- https://github.com/micronutrientsupport/micronutrient-support-tool/blob/develop/src/app/apiAndObjects/api/api.service.ts#L69
- https://github.com/micronutrientsupport/micronutrient-support-tool/blob/develop/src/app/apiAndObjects/api/api.service.ts#L69
-

**Comment by jon571** [comment]
@bgsandan

**Comment by bgsandan** [comment]
We need to ensure that there is no more mock data being used in the diet sections of the app (baseline, projections, scenarios).  It should all now be using live data

**Comment by Fuhji** [comment]
this seems like it should be split into multiple issues for each mock-->live endpoint and labelled with priority 1, for next weeks sprint?

**Comment by Fuhji** [comment]
- [x] Household Histogram data - National overview card
- [x] Monthly food groups - Monthly food card
- [x] Current composition - Dietary change page
- [x] Current consumption - Dietary change page
- [x] Diet change composition - Dietary change page
- [x] Diet change consumption - Dietary change page
- [x] Diet change food items - Dietary change page

**Comment by Fuhji** [comment]
@bgsandan  is Biomarker API/data available now?

**Comment by bgsandan** [comment]
Not really, so looks like this was an easy issue for now! 🙂

**Comment by Fuhji** [comment]
gui using live api where available, dummy data where not available, closing issue
