### ISSUE TITLE
Monthly food groups component needs updating to use new live data structure.

### ISSUE THREAD

**Issue by TheWalnutEffect** [micronutrientsupport/micronutrient-support-tool#609]
This affects the table, graph and download etc.

Note: The foodGroup dictionary is currently mocked, so the live MonthlyFoodGroup object's foodGroup won't match up and will be null until this dictionary is live.  It's probably better to leave this task until this is live too.

**Comment by jon571** [comment]
> is this endpoint live now so unblock this issue?
@bgsandan 

You could temporarily use just the food group id for the food name, until we get the dictionary.
