### ISSUE TITLE
Household data map view card snags

### ISSUE THREAD

**Issue by LouiseAnder** [micronutrientsupport/micronutrient-support-tool#620]
https://develop--micronutrientsupport-tool.netlify.app/quick-maps/diet/baseline?country-id=MWI&mnd-id=Ca&measure=diet&age-gender-group-id=WRA (opened in firefox)

- [x]  Colour ramp and legend need to reflect the loaded data - suggest try quartiles or quintiles (i.e. four or five categories) as giving a sensible number relative to the subdivisions being shown.

- [x] Is the map gonig to be exportable, as for other figures? (this may be another issue?)

- [x]  A more informative title would be good so that when the map is exported and can be taken from the data (e.g. Median apparent intake of calcium by households at District level, Malawi). 

- [x]  Map needs units displayed, which should be being calculated as Adult Female Equivalent (AFE) for the household data pages, for example mg/AFE/day

Example of suggested presentation for hover box:
![image](https://user-images.githubusercontent.com/39411049/143427374-5faeccce-8c34-4326-8d5e-accdb53df255.png) (data fields should be present in API response but please shout if unclear)

**Comment by bgsandan** [comment]
Last two boxes should now be ready to implement

**Comment by Fuhji** [comment]
`District` level - is this always static or is there an endpoint to use? @bgsandan

**Comment by bgsandan** [comment]
@Fuhji let's go with your suggestion for now :smile:

**Comment by Fuhji** [comment]
(which one? 🙃 )

**Comment by bgsandan** [comment]
`or can we use dataLevel as a proxy i.e. Household = district, country = Country?`

**Comment by Fuhji** [comment]
![image](https://user-images.githubusercontent.com/4210022/143433727-2d68c1c5-ef26-4f7c-bd09-c9aeeeda0160.png)

Available properties to display:
```
areaName: "Nkhotakota"
areaType: "admin"
deficientPercentage: 14.77
deficientValue: 632.60775513785
dietarySupply: 915.7102039727778
unit: "mg"
```

Unsure how to access correct data for last section (88/88) ? Household count?

**Comment by bgsandan** [comment]
The API is returning more fields than that.  They may not be implemented in the API response model in the app

![](https://user-images.githubusercontent.com/39411049/143434405-6e9864df-e379-402b-bb26-40e45edb6e79.png)

you would then be looking for `deficientCount` / `householdCount`

**Comment by Fuhji** [comment]
Thanks, will look to updating what properties are accessed by app api

**Comment by Fuhji** [comment]
not to nitpick, but several params return numbers as strings e.g. householdCount.... surely they should be `number` not `string` ?

**Comment by Fuhji** [comment]
Jon has just converted them at front end, but wondered if this was intentional (and if so why?)

**Comment by bgsandan** [comment]
@Fuhji mainly down to default behaviour of the platforms involved:

```
Because JavaScript doesn't have support for 64-bit integers node-postgres cannot confidently parse int8 data type results as numbers because if you have a huge number it will overflow and the result you'd get back from node-postgres would not be the result in the database. That would be a very bad thing so node-postgres just returns int8 results as strings and leaves the parsing up to you.
```

[https://github.com/brianc/node-pg-types](https://github.com/brianc/node-pg-types)

We _probably_ don't have any data stored that is likely to overflow but it's not something that has been explicitly forced/co-erced at the API layer so it is just returning in its default format as that is the default behaviour for the stack of libraries in use

Ideally we should probably make the API return safe numeric values but it hasn't made it high enough up the priority list yet :shrug:

**Comment by bgsandan** [comment]
Though why the simple values like household counts are defaulting to big integers is probably an issue at the DB architecture layer...
