### ISSUE TITLE
Histogram

### ISSUE THREAD

**Issue by LouiseAnder** [micronutrientsupport/micronutrient-support-tool#622]
https://develop--micronutrientsupport-tool.netlify.app/quick-maps/diet/baseline?country-id=MWI&mnd-id=Ca&measure=diet&age-gender-group-id=WRA (using firefox)

- [x] - units should be Calcium (mg/AFE/day) for household data, not _per capita_ (e.g. x axis label)

- [x] - title needs to be more informative for export, as per map card and food item cards (can be consistent with those except 'histogram' in title

- [x] tooltip on threshold should say which group the tooltip applies to
- [ ] set min x to be lower than threshold & max x higher than threshold to ensure threshold line is visible.

**Comment by Sveouu** [comment]
Re-opening , threshold appearance needs resolving

**Comment by bgsandan** [comment]
Thresholds now resolved
