### ISSUE TITLE
heading banner text on baseline page

### ISSUE THREAD

**Issue by LouiseAnder** [micronutrientsupport/micronutrient-support-tool#624]
https://develop--micronutrientsupport-tool.netlify.app/quick-maps/diet/baseline?country-id=MWI&mnd-id=Ca&measure=diet&age-gender-group-id=WRA  (on firefox)

- Can we add some context sensitive information to this? 
e.g.  Median apparent intake of calcium is xx mg/AFE/day for the whole dataset, based upon xx,xxx household data records (cite data) and local food composition table (cite numbers from each FCT used)

Where cite numbers from each FCT used can this be something like this example?
**XX from FCT1, xx from FCT2,....xx from FCT_k_, xx unmatched**

**Comment by Fuhji** [comment]
Current text:

>  These data present ‘apparent intake’ of micronutrients, derived from socio-economic surveys conducting recall of household-level data. These proxy for consumption is joined to locally relevant food composition table data. 

Suggested change to:

> Median apparent intake of `{{ micronutrient }}` is `{{ dailyMnContribution }}` mg/AFE/day for the whole dataset, based upon {{ household data record count @rbroth @jon571 is this available? }} and local food composition table.

I'm afraid I don't understand the example of:

> XX from FCT1, xx from FCT2,....xx from FCT_k_, xx unmatched

@bgsandan @LouiseAnder

**Comment by bgsandan** [comment]
`XX from FCT1, xx from FCT2,....xx from FCT_k_, xx unmatched`

Not sure we currently have the data returned to be able to state this.  What we do have in the data-sources endpoint is the data to add a "more info" modal as there is in the projections page with basic info/details of the datasets used.

We can improve in the future, but for now we can display the name, description and metatdata url for each of the datasets in that modal (see top comment in: [https://github.com/micronutrientsupport/micronutrient-support-tool/issues/546#issue-989863243)](https://github.com/micronutrientsupport/micronutrient-support-tool/issues/546#issue-989863243))

**Comment by rbroth** [comment]
> Median apparent intake of `{{ micronutrient }}` is `{{ dailyMnContribution }}` mg/AFE/day for the whole dataset, based upon {{ household data record count @rbroth @jon571 is this available? }} and local food composition table.

To clarify, you mean the total number of households in that survey, correct? I don't think we have a view/endpoint for that yet

**Comment by LouiseAnder** [comment]
Yes, @rbroth  that's what a I meant re your query

@bgsandan  yes, was thinking here of the cascading FCT selection schema

**Comment by bgsandan** [comment]
Closed for now by #658
