### ISSUE TITLE
Add a line graph to the monthly food chart.

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#645]
As well as the stacked bar chart, display the same data as a line chart with month along the x axis, percentage on the y axis and an individual series line for each food group.

*    [x]  Update "Monthly summary Chart" tab title to "Stacked bar"
*    [x]  Add new tab for "Line chart"
*    [x]  Add line chart displaying the same data as the stacked bar chart

**Comment by Sveouu** [comment]
merged into develop
