### ISSUE TITLE
Changing country in simple dietary change scenarios doesn't clear previous map data

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#652]
Choropleth map data doesn't clear when selecting a new country.  The data appears to just get appended to the previous data:

![](https://user-images.githubusercontent.com/39411049/138422504-681f86a9-d313-426a-8301-ddb9b648746a.png)

**Comment by Fuhji** [comment]
@bgsandan is there a link to where this can be repeated? on my local branch and also in the develop preview im not seeing this?

e.g.
1) https://develop--micronutrientsupport-tool.netlify.app/quick-maps/diet/baseline?country-id=ETH&mnd-id=Ca&measure=diet&age-gender-group-id=WRA
2) https://develop--micronutrientsupport-tool.netlify.app/quick-maps/diet/baseline?country-id=ZAF&mnd-id=Ca&measure=diet&age-gender-group-id=WRA

This is baseline map changing country

**Comment by bgsandan** [comment]
Hi @Fuhji.  It is in the "simple dietary change scenarios" page, so if you go to e.g.:

[https://develop--micronutrientsupport-tool.netlify.app/quick-maps/diet/dietary-change?country-id=ETH&mnd-id=Ca&measure=diet&age-gender-group-id=WRA&sm=0&si=1594.01-54](https://develop--micronutrientsupport-tool.netlify.app/quick-maps/diet/dietary-change?country-id=ETH&mnd-id=Ca&measure=diet&age-gender-group-id=WRA&sm=0&si=1594.01-54)

and then change the country in the sidebar, both maps will still show the data for Ethiopia in addition to the newly selected country:

![](https://user-images.githubusercontent.com/39411049/143035703-37bc34bf-f4b6-47a7-a0fe-3a7942de4068.png)

**Comment by bgsandan** [comment]
Hi @Fuhji.  It is in the "simple dietary change scenarios" page, so if you go to e.g.:

[https://develop--micronutrientsupport-tool.netlify.app/quick-maps/diet/dietary-change?country-id=ETH&mnd-id=Ca&measure=diet&age-gender-group-id=WRA&sm=0&si=1594.01-54](https://develop--micronutrientsupport-tool.netlify.app/quick-maps/diet/dietary-change?country-id=ETH&mnd-id=Ca&measure=diet&age-gender-group-id=WRA&sm=0&si=1594.01-54)

and then change the country in the sidebar, both maps will still show the data for Ethiopia in addition to the newly selected country:

![](https://user-images.githubusercontent.com/39411049/143035703-37bc34bf-f4b6-47a7-a0fe-3a7942de4068.png)
