### ISSUE TITLE
Intervention summary card

### ISSUE THREAD

**Issue by pautva** [micronutrientsupport/micronutrient-support-tool#670]
# Latest updates to the card

* Removed rename option 
* Add last modified date
* Remove status chips
* Added intervention ID
* Add intervention description

# User story
As an economist reviewing new interventions, I want to see a high-level overview of the interventions that have been created, so that I can see which ones still need reviewing.

# Screenshot
![Property 1=Simplified - Version 1](https://user-images.githubusercontent.com/72566636/176228458-d4f5f8e8-d851-4616-ba33-06bc5d653d61.png)

<details>
<summary> View card location</summary>
<br>

![Intervention Card](https://user-images.githubusercontent.com/72566636/143005877-43e80c5a-5a0a-4351-aeaa-d3f52210b49d.png)
</details>

# Links

* [Prototype link](https://www.figma.com/proto/swhv1D7WScZwDE5KKYkkaE/BMGF-Maps?page-id=0%3A1&node-id=3218%3A2&viewport=288%2C48%2C0.04&scaling=contain&starting-point-node-id=3218%3A2&show-proto-sidebar=1&hide-ui=1)
* [MIRO Board - MAPS Cost Calculator Plan](https://miro.com/app/board/uXjVODLlG_E=/?invite_link_id=430726996210)

# Card states

<details>
<summary> Delete modal</summary>
<br>

![delete-modal](https://user-images.githubusercontent.com/72566636/143023408-920d13ab-960a-454b-80cd-648fea6a9a3a.png)
</details>

## Description
Users will be able to see high-level details of the intervention they created. 

# Acceptance criteria
- [x] Card shows intervention name
- [x] Card shows the base year (the year intervention was created)
- [x] If the assumptions and costs have been reviewed, I can see the "10-year total cost".
- [x] I can see whether the intervention Assumptions have been reviewed or not
- [x] I can see whether the intervention Costs have been reviewed or not
- [x] I can delete the intervention
- [x] I can Review intervention details

**Comment by Fuhji** [comment]
@pautva is baseyear is null, which year should be used?

**Comment by Fuhji** [comment]
complete
