### ISSUE TITLE
Replace Lorem Ipsum text in sections of the app to be released

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#688]
### Projections to 2050

"Projected <Micronutrient> availability to 2050" card info
- [x] https://develop--micronutrientsupport-tool.netlify.app/quick-maps/diet/projection?country-id=MWI&mnd-id=Ca&measure=diet&age-gender-group-id=WRA&sm=0&si=
![image](https://user-images.githubusercontent.com/39411049/143428685-d6888519-cb03-4aad-9715-9c925c44a60d.png)

"Projected Food Sources for <Micronutrient>" card info
- [ ] https://develop--micronutrientsupport-tool.netlify.app/quick-maps/diet/projection?country-id=MWI&mnd-id=Ca&measure=diet&age-gender-group-id=WRA&sm=0&si=
![image](https://user-images.githubusercontent.com/39411049/143428807-77754a73-7a6b-415d-b52c-fa8938048c5c.png)

### Simple Dietary Change Scenarios

Summary header bar text
- [x] https://develop--micronutrientsupport-tool.netlify.app/quick-maps/diet/dietary-change?country-id=MWI&mnd-id=Ca&measure=diet&age-gender-group-id=WRA&sm=0&si=
![image](https://user-images.githubusercontent.com/39411049/143428908-ba26e1cc-d34b-4805-9e6d-31f508286efc.png)

- [ ] Scenario card about tab
![image](https://user-images.githubusercontent.com/39411049/143429004-a5e9d9e5-80ec-47cc-a69d-6c9d1c6dee3b.png)

### Explore Cost Effectiveness Scenarios

Summary header bar text
- [x] #717
![image](https://user-images.githubusercontent.com/39411049/143428908-ba26e1cc-d34b-4805-9e6d-31f508286efc.png)

### Home Page

Maps Tool Portal
- [x] https://develop--micronutrientsupport-tool.netlify.app/
![image](https://user-images.githubusercontent.com/39411049/143428276-c9fcc4b1-818c-4c2b-9bdd-1a43454d9d12.png)

### Project Help

Project help page
- [x] https://develop--micronutrientsupport-tool.netlify.app/help
![image](https://user-images.githubusercontent.com/39411049/143428408-a8cf8d08-2201-4545-b070-4bcb0bcad3fd.png)

### Project Objectives

Project objectives page
- [x] https://develop--micronutrientsupport-tool.netlify.app/project-objectives
![image](https://user-images.githubusercontent.com/39411049/143428488-96f9c681-7cee-4f65-a3cd-fe6544975ed3.png)

**Comment by bgsandan** [comment]
@LouiseAnder Can you advise / help with text for any of the above?

**Comment by Fuhji** [comment]
Are there any updates to replacement text for these areas ?

**Comment by LouiseAnder** [comment]
https://develop--micronutrientsupport-tool.netlify.app/help

The MAPS project is currently developing resources to support users which include (1) a glossary of terms, (2) 'walk through' examples of the interface options, and a case study of the interpretation of each example, and (3) our data analysis methods. These resources will be linked at appropriate locations in the tool, or can be reached via this link.

@bgsandan  @Fuhji

**Comment by LouiseAnder** [comment]
https://develop--micronutrientsupport-tool.netlify.app/project-objectives

Please use content from https://micronutrient.support/about/ or link directly, so we may avoid having version control problems / need update only in one place. 

@bgsandan   @Fuhji

**Comment by LouiseAnder** [comment]
![image](https://user-images.githubusercontent.com/65279285/144252672-5c04c5fe-735b-48fe-a34d-51621e1ec1a2.png)

https://develop--micronutrientsupport-tool.netlify.app/

The MAPS tool allows the user to choose pre-loaded data to examine micronutrient deficiency data, including projections. The user can also explore cost and effectiveness options to reduce micronutrient deficiencies through model functionalities. Please note, some functionality is still under pre-release development. Please contact us for more details. 

@bgsandan  @Fuhji

**Comment by LouiseAnder** [comment]
https://develop--micronutrientsupport-tool.netlify.app/quick-maps/diet/dietary-change?country-id=MWI&mnd-id=Ca&measure=diet&age-gender-group-id=WRA&sm=0&si=

This functionality allows full flexibility to adjust either the composition of food item(s) in the diet, or their consumption. Please note that this functionality does not impose any rule-based limitations, so the results you generate should be used with care. We suggest using cost and effectiveness modelling functionality in MAPS to examine the plausibility of any options of particular interest.

**Comment by LouiseAnder** [comment]
@bgsandan  and @Fuhji  the two top cards linked through seem to already have text loaded?

I think this provides input or response to all requests above, apart from one that would benefit from @kpitten  input flagged?

**Comment by kpitten** [comment]
How about something like this (feel free to edit!):
This functionality allows users to estimate the effectiveness, cost, and cost-effectiveness of micronutrient interventions over a 10-year modeling time horizon. Comparisons of effectiveness, cost, and cost-effectiveness across interventions is possible after users have generated these estimates for more than one intervention.

**Comment by LouiseAnder** [comment]
Really nice @kpitten  I think that can definitely be used :-) 

there'll be a chance to check and review when all these edits are made, as well, so you can adjust if it doesn't look quite right in context.

**Comment by Sveouu** [comment]
Thanks @LouiseAnder 

I have uodated those sections that are ticked off, however the following woudl still require text:

 https://develop--micronutrientsupport-tool.netlify.app/quick-maps/diet/projection?country-id=MWI&mnd-id=Ca&measure=diet&age-gender-group-id=WRA&sm=0&si=

https://develop--micronutrientsupport-tool.netlify.app/quick-maps/diet/projection?country-id=MWI&mnd-id=Ca&measure=diet&age-gender-group-id=WRA&sm=0&si=

Scenario card comparison about tab
https://develop--micronutrientsupport-tool.netlify.app/quick-maps/diet/dietary-change?country-id=MWI&mnd-id=Ca&measure=diet&age-gender-group-id=WRA&sm=0&si=

@bgsandan @Fuhji

**Comment by LouiseAnder** [comment]
hi @Sveouu  the top one has text when I open it...
![image](https://user-images.githubusercontent.com/65279285/144412093-02645c5b-7af8-4ef7-b3fc-4da0c0f57e9d.png)

Or do you mean somewhere else?
thanks!

**Comment by Sveouu** [comment]
hi @LouiseAnder 
I mean the "about section" of the cards:
![image](https://user-images.githubusercontent.com/72437441/144425613-ef7d8ad8-5fd4-41ad-a8c9-ea6aab8ddd37.png)

**Comment by LouiseAnder** [comment]
thanks @Sveouu !

this needs some wise words from @sherwingabr :)

**Comment by LouiseAnder** [comment]
PS., I've provided text for https://develop--micronutrientsupport-tool.netlify.app/quick-maps/diet/dietary-change?country-id=MWI&mnd-id=Ca&measure=diet&age-gender-group-id=WRA&sm=0&si=   above, again unless I've missed something @Sveouu  ??  thanks!

**Comment by sherwingabr** [comment]
Hey guys! Here's some suggested text to replace the Lorem Ipsum section:

_Availability refers to the average daily amount of a food, vitamin, or mineral available to a person. This is influenced by projections and trends in domestic production, net trade, consumer prices, per capita income, and food preferences. 

This section presents information about estimated calcium daily calcium availability through to 2050. Results are presented in milligrams per person per day. The estimates are derived from the estimated food availability projections from the IMPACT model, as well as from the estimated nutrient content of those food groups._

I hope this is useful!

**Comment by LouiseAnder** [comment]
Hi @sherwingabr that's great thank you, and for being so speedy!

I think we may just need to replace 'calcium' for 'micronutrient' and delete the first 'calcium' ? i.e. ... _calcium daily calcium_ ... -> ... _daily micronutrient_ ...  as a way of keeping the text generic for all micronutrients. 

Does that work for you?

**Comment by sherwingabr** [comment]
Hi @LouiseAnder !

Yes, sounds good! We might then also just remove the subsequent sentence, because the units might also be different (e.g. mcg vs mg) :)

**Comment by LouiseAnder** [comment]
Great, thank you @sherwingabr!

is that everything you need on that one @Sveouu    ?

**Comment by Sveouu** [comment]
@sherwingabr @LouiseAnder  
Thank you.
I updated the projection availability card, now only the **projected food sources** remains
![image](https://user-images.githubusercontent.com/72437441/144578648-c5548ad6-f10b-40bc-8e73-41a753a43c90.png)

And the about tab in the  comparison card (scenarios section)
![image](https://user-images.githubusercontent.com/72437441/144578863-2c2b64a0-89b7-4e61-98d3-20763aa013b6.png)

**Comment by Fuhji** [comment]
@Sveouu would these fixes be ready to me merged in this morning? no worries if not

**Comment by Sveouu** [comment]
yes sure. I'll push it up.  we can always add the text for the couple of outstanding ones later.

**Comment by Fuhji** [comment]
closing this issue to tidy up and creating new one with most up to date list of dummy content locations
