### ISSUE TITLE
If pick a country with no data source, the application starts showing broken content

### ISSUE THREAD

**Issue by Fuhji** [micronutrientsupport/micronutrient-support-tool#689]
Loading baseline quickmaps page for some countries either does not load, or causes the app to start showing incorrect data:

https://develop--micronutrientsupport-tool.netlify.app/quick-maps?country-id=MAR&mnd-id=Ca&measure=diet&age-gender-group-id=WRA

When selecting a country first, you cannot proceed if no diet data available. However, when changing to this country from another country which has data, the content starts to break down.

**Comment by bgsandan** [comment]
Good spot.  There are certainly some permutations that trigger an invalid data warning and/or kick you back a page (e.g. within the projections page, switching to a micronutrient that doesn't have the `inImpact` flag kicks you back to baseline).  I can't remember how to trigger it, but I'm sure there was an error modal somewhere as well

We need to detect the `data-sources` endpoint failing/displaying No-data and use that to update the routing as in the above examples
