### ISSUE TITLE
Country level data map view card snags

### ISSUE THREAD

**Issue by Fuhji** [micronutrientsupport/micronutrient-support-tool#692]
different popup for household/country level day

```
 Country level:
Region Ethiopia
Dietary Availability: <value> mg per capita per day
<Below/Above> the threshold for deficiency
```

(deficientPercentage will be 0 (above) /100 (below) for country level data)

Linked issue #620

**Comment by Fuhji** [comment]
@bgsandan Ive read this a few times and for the benefit of clarity, can you elaborate a tad on which params need which calcs? Im guessing your not suggesting divide deficientPerc by 100

**Comment by bgsandan** [comment]
A little hacky but something along the lines of

let string = \`${deficientPercentage == 100 ? 'Below' : 'Above'} the threshold for deficiency\`

**Comment by bgsandan** [comment]
A little hacky but something along the lines of

let string = \`${deficientPercentage == 100 ? 'Below' : 'Above'} the threshold for deficiency\`

**Comment by bgsandan** [comment]
Alternatively it is probably a bit more 'valid' to do `dietarySupply < deficientValue ? 'Below' : 'Above`

Either way, hope that explains what I was suggesting the content should be?
