### ISSUE TITLE
Threshold hard-coded from SSP2, should be from scenario marked as baseline and should have same color as the SSP line?

### ISSUE THREAD

**Issue by DanielLyleWilliamWarren** [micronutrientsupport/micronutrient-support-tool#722]
![image](https://user-images.githubusercontent.com/38860838/144446837-c1ec5b78-7aac-4e07-9fea-59cb772f361d.png)

**Comment by DanielLyleWilliamWarren** [comment]
@bgsandan should the threshold have same the same colour as the SSP2 (baseline) line

**Comment by bgsandan** [comment]
I'm happy to leave it the current red for now I think

**Comment by DanielLyleWilliamWarren** [comment]
> I'm happy to leave it the current red for now I think

In that case I'll close this issue.
