### ISSUE TITLE
Review intervention details: Step 6 (Monitoring information)

### ISSUE THREAD

**Issue by pautva** [micronutrientsupport/micronutrient-support-tool#738]
# User story
As an economist, I want to adjust monitoring information details, so that it matches my current projections

## Screenshot
![image](https://user-images.githubusercontent.com/72566636/151152775-9e95d288-0777-4a1d-a3b9-e623fac101c0.png)

## Description

Users can adjust monitoring information details for the upcoming 10 years.

# Resources

## Figma prototype
* [Prototype link](https://www.figma.com/proto/swhv1D7WScZwDE5KKYkkaE/BMGF-Maps?page-id=0%3A1&node-id=3218%3A2&viewport=288%2C48%2C0.04&scaling=contain&starting-point-node-id=3218%3A2&show-proto-sidebar=1&hide-ui=1)

## Miro board
* [MIRO Board - MAPS Cost Calculator Plan](https://miro.com/app/board/uXjVODLlG_E=/?invite_link_id=430726996210)

## API details

* [Intervention API walkthrough #1](https://www.loom.com/share/5264aa296cc5440f85a3e50adb8706d2?sharedAppSource=personal_library)
* [Intervention API walkthrough #2](https://www.loom.com/share/f7246657fad04875861b75d390d96244?sharedAppSource=personal_library)
* [Interventions API details.pptx](https://github.com/micronutrientsupport/micronutrient-support-tool/files/7890658/Interventions.API.details.pptx)

## Text used in the UI
TO BE ADDED

# Acceptance criteria

- [x] The default values are loaded when users open this page for the first time
- [x] All the fields are editable
- [x] Default source if GFDx
- [x] If edits are made, source changes to "User input"
- [x] Edited values are highlighted in blue
- [x] Users can Reset all the values to default (they should be asked for confirmation before doing this)

**Comment by Sveouu** [comment]
changes implemented #1061
