### ISSUE TITLE
Cant upgrade project to Angular 12 and beyond due to ngx-feedback project

### ISSUE THREAD

**Issue by Fuhji** [micronutrientsupport/micronutrient-support-tool#744]
Project cannot be upgraded to Angular 12 and beyond until the `ngs-feedback-maps` repo is updated as well

WIP branch: https://github.com/micronutrientsupport/micronutrient-support-tool/tree/stever-ng12-update

**Comment by Fuhji** [comment]
suggested replacement: https://github.com/BlazeSoftware/customer-feedback

**Comment by bgsandan** [comment]
See [https://codepen.io/andan/pen/JjLjREY](https://codepen.io/andan/pen/JjLjREY) for a basic vanilla JS usage example

**Comment by Fuhji** [comment]
upgraded to angular 13, chartjs will need refactor at some point
