### ISSUE TITLE
Text Changes: Quick MAPS baseline (household)

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#795]
e.g. [https://preview.micronutrient.support/quick-maps/diet/baseline?country-id=MWI&mnd-id=Fe&measure=diet&age-gender-group-id=WRA](https://preview.micronutrient.support/quick-maps/diet/baseline?country-id=MWI&mnd-id=Fe&measure=diet&age-gender-group-id=WRA)

![](https://user-images.githubusercontent.com/39411049/157851115-1ecb6352-af4d-4a0c-abba-5610c28b349a.png)

*   [ ] Replace card title with "Median apparent intake of \<MN> (AFE) at district level, \<country>"

![](https://user-images.githubusercontent.com/39411049/157851631-c2652195-88c5-4509-a76d-587cf25d90de.png)

*    [ ]  Replace card title with "Monthly apparent micronuntrient intake for \<MN name> by food group in \<Country>" (note MN name i.e. Iron rather than ID (Fe))

![](https://user-images.githubusercontent.com/39411049/157851962-eac38bbe-aa00-4d1b-a688-6c69bd9d6e75.png)

*    [ ]  Replace micronutrient id with micronutrient name in card title (I.e Fe -> Iron)

![](https://user-images.githubusercontent.com/39411049/157852208-f5da068f-ef2d-475f-9982-2968e7d20439.png)

*  [ ] Replace threshold line title with "Threshold for inadequacy for AFEs"

**Comment by DanielLyleWilliamWarren** [comment]
Completed by Dan S. Closing.
