### ISSUE TITLE
Create/load intervention modal

### ISSUE THREAD

**Issue by pautva** [micronutrientsupport/micronutrient-support-tool#846]
## User story

As an economist, I want to create multiple interventions, so that I can compare them.

## Screenshots

<details>
<summary>Copy and edit intervention - step 1 (select intervention template)</summary>
<br>

![Property 1=Existing Intervention](https://user-images.githubusercontent.com/72566636/176222256-316cab58-b714-4b88-a48e-7f8dbdfeca02.png)
</details>

<details>
<summary>Copy and edit intervention - step 2 (enter title and description)</summary>
<br>

![Property 1=Variant2](https://user-images.githubusercontent.com/72566636/176223409-60450e1a-01df-4a52-a970-75e0aebd1c5c.png)
</details>

<details>
<summary>Load an existing intervention - step 1(enter intervention ID)</summary>
<br>

![Property 1=Variant4](https://user-images.githubusercontent.com/72566636/176222524-a6ecd22c-d50b-4d08-8ec2-54d8594da950.png)
</details>

<details>
<summary>Load an existing intervention - step 2 (preview intervention details (title and description) and load the intervention</summary>
<br>

![Property 1=Variant5](https://user-images.githubusercontent.com/72566636/176407664-229bc704-afdf-4ecf-bbca-df7b20881bcd.png)
</details>

## Description

User should be able to switch between creating an intervention from an existing template or loading an existing intervention by and ID.

## Resources
* [Figma prototype link](https://www.figma.com/proto/swhv1D7WScZwDE5KKYkkaE/BMGF-Maps?page-id=0%3A1&node-id=3218%3A2&viewport=288%2C48%2C0.04&scaling=contain&starting-point-node-id=3218%3A2&show-proto-sidebar=1&hide-ui=1)
* [MIRO Board - MAPS Cost Calculator Plan](https://miro.com/app/board/uXjVODLlG_E=/?invite_link_id=430726996210)

## Acceptance criteria

- [x] Users can switch between copying an existing intervention and loading an intervention by ID
- [x] Users can give new interventions a name
- [x] If a description for an intervention exists, it will be loaded in the description in input field
- [x] The description field is editable
- [x] User can load interventions by ID
- [x] Clicking "Copy and Edit" will create a new intervention with a user-given name
- [x] Loading an intervention will add the specified intervention to the intervention list

**Comment by Fuhji** [comment]
closed in #852
