### ISSUE TITLE
When adding interventions use the URL query params to store an array of intervention IDs to display

### ISSUE THREAD

**Issue by Fuhji** [micronutrientsupport/micronutrient-support-tool#849]
When a user adds a new intervention to the list (on page https://develop--micronutrientsupport-tool.netlify.app/quick-maps/diet/cost-effectiveness?country-id=MWI&mnd-id=Fe&measure=diet&age-gender-group-id=WRA), add the ID to the URL as a query parameter. This may be as an array `[1,2,3`, or multiple params `intId=1&intId=2`. The format of the parameters will depend on how Angular reads and writes URL params.

When loading the intervention home page it will check the URL for query params and load the list of interventions defined by the URL array

**Comment by kerberpolis** [comment]
@Fuhji http://localhost:8100/quick-maps/diet/cost-effectiveness?country-id=MWI&mnd-id=Fe&measure=diet&age-gender-group-id=WRA&sm=0&si=&intervention_ids=1&intervention_ids=3

This link should load intervention 1 (Ethiopia) and 3 (Malawi). It displays x2 Ethiopia but displays the correct interventions if you reinitislise the component. This may have something to do with the ChangeDetectorRef.detectChanges() functon I call but I am not 100% on how it works.

#### Steps to reproduce
1. load url (same intervention displayed twice).
2. click ''Simple dietary change scenarios' button.
3. click 'Explore cost effectiveness scenarios' button.
4. Now you will see the correct displayed interventions.

**Comment by Fuhji** [comment]
The URL is using localhost so if you need to show changes from your branch make a draft pull request and use the preview URL generated. 

If its an issue with the current develop branch can update url to that also
