### ISSUE TITLE
Intervention question: Can you have multiple copies of the same default intervention i.e. 2x intervention ID1

### ISSUE THREAD

**Issue by Fuhji** [micronutrientsupport/micronutrient-support-tool#864]
Can you have multiple copies of the same default intervention i.e. 2x intervention ID1

@bgsandan @pautva

**Comment by pautva** [comment]
I think you could have multiple copies of the same default intervention. Wouldn't copying the default intervention generate a new ID for the copy? Unless you mean something else.

The use case could be: somebody makes two copies of the default intervention, then makes different adjustments to assumptions or costs in both and then compares the two.
