### ISSUE TITLE
ESLint Rules Discussion

### ISSUE THREAD

**Issue by Fuhji** [micronutrientsupport/micronutrient-support-tool#87]
If you are disabling ESLint rules continually we should review whether they are appropriate. Please add any for discussion to this issue.

**Comment by Sveouu** [comment]
chart.Dialog.compponent.ts 
 --> https://github.com/typescript-eslint/typescript-eslint/blob/v4.7.0/packages/eslint-plugin/docs/rules/ban-types.md
export interface ChartDialogData {
  // eslint-disable-next-line @typescript-eslint/ban-types
  content: object;
}

**Comment by Fuhji** [comment]
> chart.Dialog.compponent.ts
> --> https://github.com/typescript-eslint/typescript-eslint/blob/v4.7.0/packages/eslint-plugin/docs/rules/ban-types.md
> export interface ChartDialogData {
> // eslint-disable-next-line @typescript-eslint/ban-types
> content: object;
> }

We should be using Types not generic objects:

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-types.md

```
Avoid the Object and {} types, as they mean "any non-nullish value".
This is a point of confusion for many developers, who think it means "any object type".
See this comment for more information.
Avoid the object type, as it is currently hard to use due to not being able to assert that keys exist.
See microsoft/TypeScript#21732.
```
