### ISSUE TITLE
Restrict input to 2 decimal places in the interventions sections

### ISSUE THREAD

**Issue by Sveouu** [micronutrientsupport/micronutrient-support-tool#875]
In the Cost effectiveness section restrict input to display only 2 decimal places.

custom Pipes do not work.
i.e. **SigFig Pipe**

`<input type="number" matInput required value="{{ element.year8 | sigFig:6 | number }}">`

or **Decimal Pipe**
 `<input type="number" matInput required value="{{ element.year9 | number : '.2-2' }}">`

**input type="number" incompatible with [ngModel] using number pipe** [https://github.com/angular/angular/issues/22025](https://github.com/angular/angular/issues/22025)
[https://javascript.plainenglish.io/why-you-shouldnt-use-angular-pipes-with-inputs-8dc1d0e9039d](https://javascript.plainenglish.io/why-you-shouldnt-use-angular-pipes-with-inputs-8dc1d0e9039d)

Need to use Directives:
this example was the most promising among the ones I tried:
[https://stackblitz.com/edit/limit-two-digit-decimal-place?file=src%2Fapp%2Ftwo-digit-decima-number.directive.ts](https://stackblitz.com/edit/limit-two-digit-decimal-place?file=src%2Fapp%2Ftwo-digit-decima-number.directive.ts)

For now the value returned from the api has been rounded to 2 decimals by using:

`<input appDecimalInput type="number" required [value]=element.year0.toFixed(2)>`
however it is still possible to input new values with more decimals, as the Directive is not honoured.
I am not sure if the Directive is properly retrieved.

Decimals  in inputs are strings hence input type cannot be set to number.
Would expect  the following to work:
           `<input appDecimalInput type="text" [(ngModel)]="element.year7" required>`

I managed to get the stackblitz example above to work in a separate Angular project. so the issue is either with the value being input from the api or that the directive is not being accessed as expected by the component.

https://stackoverflow.com/questions/55117569/directive-doesnt-trigger-when-input-changes

**Comment by Sveouu** [comment]
branch sr_recurring_costs_dialog

**Comment by Fuhji** [comment]
@pautva @bgsandan This is fixed in #881 but is there a guideline on which inputs across the app need to restrict decimal places to 2dp? If they are only for the interventions section this will be quicker to implement and then evaluate the impact

**Comment by bgsandan** [comment]
Currently, the primary place in the app that inputs are used as opposed to static/tabulated data is the interventions section.  Can't guarantee there won't be others, but that is the current primary usage

**Comment by Fuhji** [comment]
ok, updating issue to focus on just the interventions section for now
