### ISSUE TITLE
Intervention data from the API needs to include extra information to help the front end understand the data linkages

### ISSUE THREAD

**Issue by Fuhji** [micronutrientsupport/micronutrient-support-tool#884]
Currently the data is mostly presented in `mat-table` format with `input` fields denoting where users can make changes.

### Data types:
- percentages
- integers
- floats
- US Dollars

The front end table can choose to render an input in different ways. Currently we are using the API `rowUnits` field to determine whether to display an input as either:
- number
- percentage

Example:
```html
<div *ngIf="element.rowUnits === 'number'">
    <input type="text" appDecimalInput required [value]=element.year2>
</div>
<div *ngIf="element.rowUnits === 'percent'">
    <input type="text" appDecimalInput [value]="element.year2 * 100"
(input)="element.year2 = $any($event.target).value / 100">
</div>
```

### The challenge

- inputs/values which need to calculate the sum of N other fields
<img width="399" alt="image" src="https://user-images.githubusercontent.com/4210022/178526189-60e06c01-e1cf-48d7-b2f9-ac9e38b59821.png">

- inputs which need to modify N other fields by them selves e.g. apply a percentage modifier to X and Y
<img width="443" alt="image" src="https://user-images.githubusercontent.com/4210022/178526393-6751ddd8-fd53-4f20-8dd7-100b559145cf.png">

### The potential solutions

- add parameter to API to set what type of input this field is
  - standard input
  - input based on N other fields
    - the challenge is then to create a way of defining *what* the modifer is i.e. multiply, subtract, sum

**Comment by Sveouu** [comment]
@Fuhji I am not sure that 
![image](https://user-images.githubusercontent.com/72437441/178532835-a5060293-cdbc-47c3-8d84-158d30dc67ba.png)
 needs to be an input, it shouldnt be editable, it should just display the sum of n fields, or it might not be needed at all as other dialogs, i.e. import monitoring do not have a "total costs" row.
 As far as I understand the total costs should only be output in the intervention review card.
 
![image](https://user-images.githubusercontent.com/72437441/178534213-0a59d99d-e4b7-4592-b0b5-6f4a7cfc1ad7.png)

**Comment by Fuhji** [comment]
Agreed @Sveouu that example does not need to be an input. I've updated the issue to clarify input or value

**Comment by Fuhji** [comment]
JSON logic addresses this in #1152
